/**
 * Convex Action Generator
 *
 * Generates action functions for Convex:
 * - Actions are server-side functions that can call external APIs
 * - Actions can read from the database via ctx.runQuery
 * - Actions can write to the database via ctx.runMutation
 * - Actions support external fetch calls and third-party integrations
 *
 * Generated actions include:
 * - syncExternal: Sync document with external API
 * - fetchExternal: Fetch data from external API
 * - processDocument: Process document with external service
 * - batchSync: Batch sync multiple documents
 */

import type {
  TableInfo,
  ColumnInfo,
} from '../../introspector/schema-introspector.js';
import type {
  ActionGeneratorResult,
  ConvexApiVersion,
} from '../../convex/types.js';
import { toCamelCase, toPascalCase, escapeFieldName } from '../../utils/naming.js';
import { BaseConvexGenerator } from './base-convex-generator.js';

/**
 * Options for the action generator
 */
export interface ActionGeneratorOptions {
  /**
   * Convex API version to target
   * Default: '1.30' for backwards compatibility
   */
  convexApiVersion?: ConvexApiVersion;
  /**
   * Generate example external API calls
   * Default: true
   */
  generateExampleCalls?: boolean;
  /**
   * Include internal API import for calling queries/mutations
   * Default: true
   */
  includeInternalApi?: boolean;
}

const DEFAULT_OPTIONS: ActionGeneratorOptions = {
  convexApiVersion: '1.30',
  generateExampleCalls: true,
  includeInternalApi: true,
};

/**
 * Generates Convex action functions
 */
export class ActionGenerator extends BaseConvexGenerator<ActionGeneratorOptions> {
  constructor(options: ActionGeneratorOptions = {}) {
    super(DEFAULT_OPTIONS, options);
  }

  /**
   * Generate all actions for a table
   */
  generate(table: TableInfo): ActionGeneratorResult {
    const tableName = table.tableName;
    const pascalName = toPascalCase(tableName);

    const actions: string[] = [];

    // 1. syncExternal - Sync single document with external API
    actions.push(this.generateSyncExternal(table, tableName, pascalName));

    // 2. fetchExternal - Fetch data from external API and store
    actions.push(this.generateFetchExternal(table, tableName, pascalName));

    // 3. processDocument - Process document with external service
    actions.push(this.generateProcessDocument(table, tableName, pascalName));

    // 4. batchSync - Batch sync multiple documents
    actions.push(this.generateBatchSync(table, tableName, pascalName));

    // 5. generateEmbedding - Generate embedding if vector fields detected
    if (this.hasVectorFields(table)) {
      actions.push(this.generateEmbeddingAction(table, tableName, pascalName));
    }

    const internalApiImport = this.options.includeInternalApi
      ? '\nimport { internal } from "./_generated/api";'
      : '';

    const content = `// Generated actions for ${table.tableName}
// Do not edit this file directly - it will be overwritten
//
// Actions are server-side functions that can:
// - Call external APIs using fetch()
// - Read data using ctx.runQuery()
// - Write data using ctx.runMutation()
// - Run other actions using ctx.runAction()

import { action } from "./_generated/server";
import { v } from "convex/values";
import { api } from "./_generated/api";${internalApiImport}

${actions.join('\n\n')}
`;

    return { content, count: actions.length };
  }

  /**
   * Generate syncExternal action
   * Syncs a document with an external API
   */
  private generateSyncExternal(
    table: TableInfo,
    tableName: string,
    pascalName: string
  ): string {
    return `/**
 * Sync a ${pascalName} document with an external API
 *
 * This action:
 * 1. Fetches the document from Convex
 * 2. Sends it to an external API
 * 3. Updates the document with the response
 *
 * @example
 * \`\`\`typescript
 * // React usage:
 * import { useAction } from "convex/react";
 * import { api } from "./_generated/api";
 *
 * function Sync${pascalName}Button({ id }: { id: Id<"${tableName}"> }) {
 *   const sync = useAction(api.${tableName}.syncExternal);
 *
 *   const handleSync = async () => {
 *     const result = await sync({ id });
 *     console.log("Synced:", result);
 *   };
 *
 *   return <button onClick={handleSync}>Sync to External API</button>;
 * }
 * \`\`\`
 *
 * @param args.id - The document ID to sync
 * @param args.externalApiUrl - Optional custom API URL
 * @returns Result object with sync status and external response
 */
export const syncExternal = action({
  args: {
    id: v.id("${tableName}"),
    externalApiUrl: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    // 1. Fetch the document from Convex
    const doc = await ctx.runQuery(api.${tableName}.get, { id: args.id });

    if (!doc) {
      throw new Error(\`${pascalName} not found: \${args.id}\`);
    }

    // 2. Send to external API (replace with your actual API endpoint)
    const apiUrl = args.externalApiUrl ?? process.env.EXTERNAL_API_URL ?? "https://api.example.com/${tableName}";

    const response = await fetch(apiUrl, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        // Add your API key or auth headers here
        // "Authorization": \`Bearer \${process.env.API_KEY}\`,
      },
      body: JSON.stringify({
        id: args.id,
        data: doc,
        timestamp: Date.now(),
      }),
    });

    if (!response.ok) {
      throw new Error(\`External API error: \${response.status} \${response.statusText}\`);
    }

    const result = await response.json();

    // 3. Optionally update the document with external data
    // Uncomment and customize if your API returns data to store:
    // await ctx.runMutation(api.${tableName}.update, {
    //   id: args.id,
    //   externalId: result.externalId,
    //   syncedAt: Date.now(),
    // });

    return {
      success: true,
      documentId: args.id,
      externalResponse: result,
    };
  },
});`;
  }

  /**
   * Generate fetchExternal action
   * Fetches data from external API and stores in Convex
   */
  private generateFetchExternal(
    table: TableInfo,
    tableName: string,
    pascalName: string
  ): string {
    const createFields = this.getCreateFields(table);
    const fieldNamesComment = createFields
      .slice(0, 5)
      .map((c) => escapeFieldName(toCamelCase(c.columnName)))
      .join(', ');

    return `/**
 * Fetch ${pascalName} data from an external API and create a document
 *
 * This action:
 * 1. Fetches data from an external API
 * 2. Transforms the response to match your schema
 * 3. Creates a new document in Convex
 *
 * @example
 * \`\`\`typescript
 * // React usage:
 * import { useAction } from "convex/react";
 * import { api } from "./_generated/api";
 *
 * function Import${pascalName}({ externalId }: { externalId: string }) {
 *   const fetchExternal = useAction(api.${tableName}.fetchExternal);
 *
 *   const handleImport = async () => {
 *     const result = await fetchExternal({ externalId });
 *     console.log("Imported with ID:", result.documentId);
 *   };
 *
 *   return <button onClick={handleImport}>Import from API</button>;
 * }
 * \`\`\`
 *
 * @param args.externalId - The ID in the external system
 * @param args.externalApiUrl - Optional custom API URL
 * @returns Result object with created document ID
 */
export const fetchExternal = action({
  args: {
    externalId: v.string(),
    externalApiUrl: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    // 1. Fetch from external API
    const apiUrl = args.externalApiUrl ?? \`https://api.example.com/${tableName}/\${args.externalId}\`;

    const response = await fetch(apiUrl, {
      method: "GET",
      headers: {
        "Content-Type": "application/json",
        // "Authorization": \`Bearer \${process.env.API_KEY}\`,
      },
    });

    if (!response.ok) {
      throw new Error(\`External API error: \${response.status} \${response.statusText}\`);
    }

    const externalData = await response.json();

    // 2. Transform external data to your schema
    // Customize this mapping based on your external API response
    // Available fields: ${fieldNamesComment}${createFields.length > 5 ? '...' : ''}
    const documentData = {
      // Map your external API fields here
      // Example:
      // name: externalData.name,
      // email: externalData.email,
      ...externalData,
    };

    // 3. Create the document in Convex
    const id = await ctx.runMutation(api.${tableName}.create, documentData);

    return {
      success: true,
      documentId: id,
      externalId: args.externalId,
    };
  },
});`;
  }

  /**
   * Generate processDocument action
   * Processes a document with an external service
   */
  private generateProcessDocument(
    table: TableInfo,
    tableName: string,
    pascalName: string
  ): string {
    return `/**
 * Process a ${pascalName} document with an external service
 *
 * Use cases:
 * - AI/ML processing (sentiment analysis, classification, etc.)
 * - Image/file processing
 * - Validation with external service
 * - Enrichment from third-party data
 *
 * @example
 * \`\`\`typescript
 * // React usage:
 * import { useAction } from "convex/react";
 * import { api } from "./_generated/api";
 *
 * function Process${pascalName}({ id }: { id: Id<"${tableName}"> }) {
 *   const process = useAction(api.${tableName}.processDocument);
 *
 *   const handleProcess = async (type: string) => {
 *     const result = await process({ id, processingType: type });
 *     console.log("Processed:", result);
 *   };
 *
 *   return (
 *     <div>
 *       <button onClick={() => handleProcess("analyze")}>Analyze</button>
 *       <button onClick={() => handleProcess("validate")}>Validate</button>
 *       <button onClick={() => handleProcess("enrich")}>Enrich</button>
 *     </div>
 *   );
 * }
 * \`\`\`
 *
 * @param args.id - The document ID to process
 * @param args.processingType - Type of processing (analyze, validate, enrich, etc.)
 * @returns Result object with processing results
 */
export const processDocument = action({
  args: {
    id: v.id("${tableName}"),
    processingType: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    // 1. Fetch the document
    const doc = await ctx.runQuery(api.${tableName}.get, { id: args.id });

    if (!doc) {
      throw new Error(\`${pascalName} not found: \${args.id}\`);
    }

    const processingType = args.processingType ?? "default";

    // 2. Process based on type
    let result;

    switch (processingType) {
      case "analyze":
        // Example: Call an AI analysis API
        result = await analyzeWithAI(doc);
        break;
      case "validate":
        // Example: Validate with external service
        result = await validateExternal(doc);
        break;
      case "enrich":
        // Example: Enrich with third-party data
        result = await enrichData(doc);
        break;
      default:
        result = { processed: true, type: processingType };
    }

    // 3. Optionally update the document with processing results
    // await ctx.runMutation(api.${tableName}.update, {
    //   id: args.id,
    //   processedAt: Date.now(),
    //   processingResult: JSON.stringify(result),
    // });

    return {
      success: true,
      documentId: args.id,
      processingType,
      result,
    };
  },
});

// Helper functions for document processing
// Replace these with your actual implementations

async function analyzeWithAI(doc: Record<string, unknown>) {
  // Example: Call OpenAI, Claude, or other AI APIs
  // const response = await fetch("https://api.openai.com/v1/...", {...});
  return { analysis: "AI analysis placeholder", confidence: 0.95 };
}

async function validateExternal(doc: Record<string, unknown>) {
  // Example: Validate with external service
  return { valid: true, checks: ["format", "completeness"] };
}

async function enrichData(doc: Record<string, unknown>) {
  // Example: Enrich with third-party data
  return { enriched: true, additionalFields: {} };
}`;
  }

  /**
   * Generate batchSync action
   * Batch sync multiple documents
   */
  private generateBatchSync(
    table: TableInfo,
    tableName: string,
    pascalName: string
  ): string {
    return `/**
 * Batch sync multiple ${pascalName} documents with an external API
 *
 * This action:
 * 1. Fetches multiple documents from Convex
 * 2. Sends them in batch to an external API
 * 3. Returns sync results for each document
 *
 * Automatically batches requests to respect API rate limits and prevent timeouts.
 *
 * @example
 * \`\`\`typescript
 * // React usage:
 * import { useAction } from "convex/react";
 * import { api } from "./_generated/api";
 *
 * function BatchSync${pascalName}({ ids }: { ids: Array<Id<"${tableName}">> }) {
 *   const batchSync = useAction(api.${tableName}.batchSync);
 *   const [syncing, setSyncing] = useState(false);
 *
 *   const handleSync = async () => {
 *     setSyncing(true);
 *     const result = await batchSync({ ids, batchSize: 10 });
 *     console.log(\`Success: \${result.successCount} / \${result.totalProcessed}\`);
 *     setSyncing(false);
 *   };
 *
 *   return (
 *     <button onClick={handleSync} disabled={syncing}>
 *       {syncing ? "Syncing..." : \`Sync \${ids.length} items\`}
 *     </button>
 *   );
 * }
 * \`\`\`
 *
 * @param args.ids - Array of document IDs to sync
 * @param args.externalApiUrl - Optional custom API URL
 * @param args.batchSize - Number of items per batch (default: 10)
 * @returns Summary object with success/failure counts and per-item results
 */
export const batchSync = action({
  args: {
    ids: v.array(v.id("${tableName}")),
    externalApiUrl: v.optional(v.string()),
    batchSize: v.optional(v.number()),
  },
  handler: async (ctx, args) => {
    const batchSize = args.batchSize ?? 10;
    const results: Array<{ id: string; success: boolean; error?: string }> = [];

    // Process in batches to avoid overwhelming external API
    for (let i = 0; i < args.ids.length; i += batchSize) {
      const batch = args.ids.slice(i, i + batchSize);

      // Fetch all documents in this batch
      const docs = await Promise.all(
        batch.map(id => ctx.runQuery(api.${tableName}.get, { id }))
      );

      // Send batch to external API
      const apiUrl = args.externalApiUrl ?? process.env.EXTERNAL_API_URL ?? "https://api.example.com/${tableName}/batch";

      try {
        const response = await fetch(apiUrl, {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            // "Authorization": \`Bearer \${process.env.API_KEY}\`,
          },
          body: JSON.stringify({
            documents: docs.filter(d => d !== null),
            timestamp: Date.now(),
          }),
        });

        if (response.ok) {
          batch.forEach(id => results.push({ id, success: true }));
        } else {
          const errorText = await response.text();
          batch.forEach(id => results.push({
            id,
            success: false,
            error: \`API error: \${response.status}\`
          }));
        }
      } catch (error) {
        batch.forEach(id => results.push({
          id,
          success: false,
          error: error instanceof Error ? error.message : "Unknown error"
        }));
      }

      // Optional: Add delay between batches to respect rate limits
      if (i + batchSize < args.ids.length) {
        await new Promise(resolve => setTimeout(resolve, 100));
      }
    }

    const successCount = results.filter(r => r.success).length;

    return {
      totalProcessed: results.length,
      successCount,
      failureCount: results.length - successCount,
      results,
    };
  },
});`;
  }

  /**
   * Generate embedding action for tables with vector fields
   */
  private generateEmbeddingAction(
    table: TableInfo,
    tableName: string,
    pascalName: string
  ): string {
    const vectorFields = this.getVectorFields(table);
    const textFields = this.getTextFields(table);
    const vectorFieldName =
      vectorFields.length > 0
        ? escapeFieldName(toCamelCase(vectorFields[0].columnName))
        : 'embedding';
    const textFieldName =
      textFields.length > 0
        ? escapeFieldName(toCamelCase(textFields[0].columnName))
        : 'content';

    return `/**
 * Generate embedding for a ${pascalName} document
 *
 * This action:
 * 1. Fetches the document
 * 2. Extracts text content for embedding
 * 3. Calls an embedding API (OpenAI, Cohere, etc.)
 * 4. Updates the document with the embedding vector
 */
export const generateEmbedding = action({
  args: {
    id: v.id("${tableName}"),
    embeddingModel: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    // 1. Fetch the document
    const doc = await ctx.runQuery(api.${tableName}.get, { id: args.id });

    if (!doc) {
      throw new Error(\`${pascalName} not found: \${args.id}\`);
    }

    // 2. Extract text content for embedding
    // Customize this based on which fields should be embedded
    const textContent = doc.${textFieldName} ?? "";

    if (!textContent) {
      throw new Error("No text content to embed");
    }

    // 3. Generate embedding via external API
    const model = args.embeddingModel ?? "text-embedding-3-small";

    // Example: Using OpenAI embeddings API
    const response = await fetch("https://api.openai.com/v1/embeddings", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": \`Bearer \${process.env.OPENAI_API_KEY}\`,
      },
      body: JSON.stringify({
        model,
        input: textContent,
      }),
    });

    if (!response.ok) {
      const error = await response.text();
      throw new Error(\`Embedding API error: \${response.status} - \${error}\`);
    }

    const result = await response.json();
    const embedding = result.data[0].embedding;

    // 4. Update document with embedding
    await ctx.runMutation(api.${tableName}.update, {
      id: args.id,
      ${vectorFieldName}: embedding,
    });

    return {
      success: true,
      documentId: args.id,
      dimensions: embedding.length,
      model,
    };
  },
});

/**
 * Batch generate embeddings for multiple ${pascalName} documents
 */
export const batchGenerateEmbeddings = action({
  args: {
    ids: v.array(v.id("${tableName}")),
    embeddingModel: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const results: Array<{ id: string; success: boolean; error?: string }> = [];

    for (const id of args.ids) {
      try {
        await ctx.runAction(api.${tableName}.generateEmbedding, {
          id,
          embeddingModel: args.embeddingModel,
        });
        results.push({ id, success: true });
      } catch (error) {
        results.push({
          id,
          success: false,
          error: error instanceof Error ? error.message : "Unknown error",
        });
      }
    }

    return {
      totalProcessed: results.length,
      successCount: results.filter(r => r.success).length,
      results,
    };
  },
});`;
  }

  /**
   * Check if table has vector/embedding fields
   */
  private hasVectorFields(table: TableInfo): boolean {
    return this.getVectorFields(table).length > 0;
  }

  /**
   * Get vector/embedding fields from table
   */
  private getVectorFields(table: TableInfo): ColumnInfo[] {
    const vectorFieldPatterns = [
      /embedding/i,
      /vector/i,
      /features?$/i,
      /encode/i,
    ];

    return table.columns.filter((col) => {
      const name = col.columnName.toLowerCase();
      const cleanType = col.dataType.split('(')[0].toLowerCase();
      const nameMatches = vectorFieldPatterns.some((pattern) =>
        pattern.test(name)
      );
      const isArrayType = col.dataType.includes('[]') || cleanType === 'vector';
      return nameMatches || isArrayType;
    });
  }

  /**
   * Get text fields from table
   */
  private getTextFields(table: TableInfo): ColumnInfo[] {
    return table.columns.filter((col) => {
      const cleanType = col.dataType.split('(')[0].toLowerCase();
      return ['text', 'varchar', 'character varying', 'citext'].includes(
        cleanType
      );
    });
  }

}
