/**
 * Convex Auth Scaffolding Generator
 *
 * If the source schema contains a users table with an email column
 * and a password-like column (password, password_hash, hashed_password),
 * this generator produces starter auth files using @convex-dev/auth:
 *
 *   - convex/auth.ts   — convexAuth({ providers: [Password] }) setup
 *   - convex/auth.config.ts — site URL + provider config
 *
 * Install: npm i @convex-dev/auth @auth/core
 *
 * Docs: https://labs.convex.dev/auth
 */

import type { TableInfo } from '../../introspector/schema-introspector.js';

const EMAIL_COLUMN_PATTERNS = ['email', 'email_address', 'user_email'];
const PASSWORD_COLUMN_PATTERNS = [
  'password',
  'password_hash',
  'hashed_password',
  'passwd',
  'pwd',
];
const USERNAME_COLUMN_PATTERNS = [
  'username',
  'user_name',
  'handle',
  'screen_name',
];
const NAME_COLUMN_PATTERNS = [
  'name',
  'full_name',
  'display_name',
  'first_name',
];

interface AuthAnalysis {
  detected: boolean;
  usersTable: string | null;
  hasEmail: boolean;
  hasPassword: boolean;
  hasUsername: boolean;
  hasName: boolean;
  emailField: string | null;
  nameField: string | null;
}

export function detectAuthTable(tables: TableInfo[]): AuthAnalysis {
  const analysis: AuthAnalysis = {
    detected: false,
    usersTable: null,
    hasEmail: false,
    hasPassword: false,
    hasUsername: false,
    hasName: false,
    emailField: null,
    nameField: null,
  };

  // Look for a users/accounts/members table
  const candidateTables = tables.filter((t) =>
    [
      'users',
      'user',
      'accounts',
      'account',
      'members',
      'member',
      'profiles',
    ].includes(t.tableName.toLowerCase())
  );

  for (const table of candidateTables) {
    const cols = table.columns.map((c) => c.columnName.toLowerCase());
    const hasEmail = cols.some((c) => EMAIL_COLUMN_PATTERNS.includes(c));
    const hasPassword = cols.some((c) =>
      PASSWORD_COLUMN_PATTERNS.some((p) => c === p)
    );

    if (hasEmail && hasPassword) {
      analysis.detected = true;
      analysis.usersTable = table.tableName;
      analysis.hasEmail = true;
      analysis.hasPassword = true;

      const emailCol = table.columns.find((c) =>
        EMAIL_COLUMN_PATTERNS.includes(c.columnName.toLowerCase())
      );
      const nameCol = table.columns.find((c) =>
        NAME_COLUMN_PATTERNS.some((p) => c.columnName.toLowerCase() === p)
      );
      const usernameCol = table.columns.find((c) =>
        USERNAME_COLUMN_PATTERNS.includes(c.columnName.toLowerCase())
      );

      analysis.emailField = emailCol?.columnName ?? 'email';
      analysis.hasName = !!nameCol;
      analysis.nameField = nameCol?.columnName ?? null;
      analysis.hasUsername = !!usernameCol;
      break;
    }
  }

  return analysis;
}

export interface AuthGeneratorResult {
  detected: boolean;
  authTs: string;
  authConfigTs: string;
  installCommand: string;
  schemaNote: string;
}

/**
 * Generates auth.ts and auth.config.ts for Convex Auth (Password provider).
 * Returns detected=false if no auth-eligible users table is found.
 */
export function generateAuth(tables: TableInfo[]): AuthGeneratorResult {
  const analysis = detectAuthTable(tables);

  if (!analysis.detected) {
    return {
      detected: false,
      authTs: '',
      authConfigTs: '',
      installCommand: '',
      schemaNote: '',
    };
  }

  const installCommand = 'npm i @convex-dev/auth @auth/core';

  const authTs = `/**
 * Convex Auth Configuration
 *
 * Auto-generated by SunSetter AQM+.
 * A users table with email+password columns was detected in your source schema.
 *
 * ${installCommand}
 *
 * Then run: npx @convex-dev/auth
 *
 * Docs: https://labs.convex.dev/auth
 */

import { convexAuth } from "@convex-dev/auth/server";
import { Password } from "@convex-dev/auth/providers/Password";

export const { auth, signIn, signOut, store, isAuthenticated } = convexAuth({
  providers: [
    Password({
      // Optionally add email verification:
      // verify: ResendOTP,
      //
      // Optionally customize the profile saved to the users table:
      // profile(params) {
      //   return {
      //     email: params.email as string,
      //     name: params.name as string,
      //   };
      // },
    }),
  ],
});
`;

  const authConfigTs = `/**
 * Convex Auth site configuration
 *
 * Set SITE_URL to your deployed frontend URL.
 * Docs: https://labs.convex.dev/auth/setup/manual
 */

const config = {
  providers: [
    {
      domain: process.env.CONVEX_SITE_URL,
      applicationID: "convex",
    },
  ],
};

export default config;
`;

  const schemaNote = `
// ─── Convex Auth ─────────────────────────────────────────────────────────────
// SunSetter detected a users table with email + password columns.
// To use Convex Auth, spread authTables into your defineSchema:
//
//   import { authTables } from "@convex-dev/auth/server";
//   export default defineSchema({ ...authTables, /* your tables */ });
//
// The authTables spread adds users, authSessions, and supporting tables.
// Your existing "users" table data should be migrated or reconciled.
// ─────────────────────────────────────────────────────────────────────────────`;

  return {
    detected: true,
    authTs,
    authConfigTs,
    installCommand,
    schemaNote,
  };
}
