/**
 * Convex Component Config Generator
 *
 * Generates convex/convex.config.ts that wires up Convex components
 * based on schema analysis. Always includes the migrations component.
 * Detects write-heavy patterns to suggest rate limiter, and data-heavy
 * patterns to suggest the aggregate component.
 *
 * Component docs:
 * - https://docs.convex.dev/components/using-components
 * - https://www.convex.dev/components/rate-limiter
 * - https://www.convex.dev/components/aggregate
 * - https://www.convex.dev/components/migrations
 */

import type { TableInfo } from '../../introspector/schema-introspector.js';

// Tables with many inbound foreign keys are write-heavy (many writers touch them)
const WRITE_HEAVY_FK_THRESHOLD = 3;

// Tables that look like analytics / event logs (no FKs, timestamp-heavy)
const ANALYTICS_TIMESTAMP_PATTERNS = [
  'created_at',
  'event_at',
  'timestamp',
  'occurred_at',
  'logged_at',
];

interface ComponentAnalysis {
  needsRateLimiter: boolean;
  needsAggregate: boolean;
  writeHeavyTables: string[];
  analyticsTables: string[];
}

function analyzeForComponents(tables: TableInfo[]): ComponentAnalysis {
  const analysis: ComponentAnalysis = {
    needsRateLimiter: false,
    needsAggregate: false,
    writeHeavyTables: [],
    analyticsTables: [],
  };

  // Count inbound FK references per table
  const inboundFKCount: Record<string, number> = {};
  for (const table of tables) {
    for (const fk of table.foreignKeys ?? []) {
      const ref = fk.referencedTable;
      inboundFKCount[ref] = (inboundFKCount[ref] ?? 0) + 1;
    }
  }

  for (const table of tables) {
    const colNames = table.columns.map((c) => c.columnName.toLowerCase());

    // Write-heavy: many other tables FK into this one
    const inbound = inboundFKCount[table.tableName] ?? 0;
    if (inbound >= WRITE_HEAVY_FK_THRESHOLD) {
      analysis.needsRateLimiter = true;
      analysis.writeHeavyTables.push(table.tableName);
    }

    // Analytics pattern: no FKs + timestamp column + many rows implied
    const hasNoFKs = (table.foreignKeys ?? []).length === 0;
    const hasTimestamp = colNames.some((n) =>
      ANALYTICS_TIMESTAMP_PATTERNS.some((p) => n === p || n.endsWith(`_${p}`))
    );
    if (hasNoFKs && hasTimestamp && table.columns.length >= 4) {
      analysis.needsAggregate = true;
      analysis.analyticsTables.push(table.tableName);
    }
  }

  return analysis;
}

export interface ComponentConfigResult {
  content: string;
  components: string[];
  installCommand: string;
}

/**
 * Generates a convex/convex.config.ts that registers detected components.
 * The migrations component is always included.
 */
export function generateComponentConfig(
  tables: TableInfo[]
): ComponentConfigResult {
  const analysis = analyzeForComponents(tables);

  const imports: string[] = [
    'import { defineApp } from "convex/server";',
    'import migrations from "@convex-dev/migrations/convex.config.js";',
  ];
  const uses: string[] = ['app.use(migrations);'];
  const components: string[] = ['migrations'];

  if (analysis.needsRateLimiter) {
    imports.push(
      'import rateLimiter from "@convex-dev/rate-limiter/convex.config.js";'
    );
    uses.push('app.use(rateLimiter);');
    components.push('rate-limiter');
  }

  if (analysis.needsAggregate) {
    imports.push(
      'import aggregate from "@convex-dev/aggregate/convex.config.js";'
    );
    // One aggregate instance per analytics table
    for (const tableName of analysis.analyticsTables) {
      uses.push(`app.use(aggregate, { name: "aggregate_${tableName}" });`);
    }
    components.push('aggregate');
  }

  const pkgs = [
    '@convex-dev/migrations',
    analysis.needsRateLimiter ? '@convex-dev/rate-limiter' : null,
    analysis.needsAggregate ? '@convex-dev/aggregate' : null,
  ].filter(Boolean) as string[];

  const installCommand = `npm i ${pkgs.join(' ')}`;

  const rateLimiterNote = analysis.needsRateLimiter
    ? `
// Rate limiter is suggested because the following tables have many inbound
// foreign keys (high write contention): ${analysis.writeHeavyTables.join(', ')}
// Define your rate limits in a separate convex/rateLimits.ts file.
// See: https://github.com/get-convex/rate-limiter#readme`
    : '';

  const aggregateNote = analysis.needsAggregate
    ? `
// Aggregate component is suggested for analytics tables detected:
// ${analysis.analyticsTables.join(', ')}
// Use these instances in your query functions for fast counts and sums.
// See: https://www.convex.dev/components/aggregate`
    : '';

  const content = `/**
 * Convex Component Configuration
 *
 * Auto-generated by SunSetter AQM+ based on schema analysis.
 * Review detected components and remove any you don't need.
 *
 * ${installCommand}
 *
 * Docs: https://docs.convex.dev/components/using-components
 */

${imports.join('\n')}

const app = defineApp();
${rateLimiterNote}${aggregateNote}

${uses.join('\n')}

export default app;
`;

  return { content, components, installCommand };
}
