/**
 * Convex HTTP Action Generator
 *
 * Generates HTTP action functions for Convex:
 * - HTTP actions expose REST-like endpoints
 * - They handle raw HTTP requests and responses
 * - Useful for webhooks, REST APIs, and third-party integrations
 *
 * Generated HTTP actions include:
 * - GET /api/[table] - List documents
 * - GET /api/[table]/:id - Get single document
 * - POST /api/[table] - Create document
 * - PATCH /api/[table]/:id - Update document
 * - DELETE /api/[table]/:id - Delete document
 * - POST /api/[table]/webhook - Handle webhooks
 */

import type { TableInfo } from '../../introspector/schema-introspector.js';
import type {
  HttpActionGeneratorResult,
  ConvexApiVersion,
} from '../../convex/types.js';
import { toPascalCase } from '../../utils/naming.js';
import { BaseConvexGenerator } from './base-convex-generator.js';

/**
 * Options for the HTTP action generator
 */
export interface HttpActionGeneratorOptions {
  /**
   * Convex API version to target
   * Default: '1.30' for backwards compatibility
   */
  convexApiVersion?: ConvexApiVersion;
  /**
   * Base path for HTTP routes
   * Default: '/api'
   */
  basePath?: string;
  /**
   * Generate CORS headers
   * Default: true
   */
  includeCors?: boolean;
  /**
   * Generate authentication middleware
   * Default: true
   */
  includeAuth?: boolean;
  /**
   * Generate webhook handler
   * Default: true
   */
  generateWebhook?: boolean;
}

const DEFAULT_OPTIONS: HttpActionGeneratorOptions = {
  convexApiVersion: '1.30',
  basePath: '/api',
  includeCors: true,
  includeAuth: true,
  generateWebhook: true,
};

/**
 * Generates Convex HTTP action functions
 */
export class HttpActionGenerator extends BaseConvexGenerator<HttpActionGeneratorOptions> {
  constructor(options: HttpActionGeneratorOptions = {}) {
    super(DEFAULT_OPTIONS, options);
  }

  /**
   * Generate all HTTP actions for a table
   */
  generate(table: TableInfo): HttpActionGeneratorResult {
    const tableName = table.tableName;
    const pascalName = toPascalCase(tableName);

    const actions: string[] = [];

    // Helper functions
    actions.push(this.generateHelpers());

    // REST endpoints
    actions.push(this.generateGetList(table, tableName, pascalName));
    actions.push(this.generateGetById(table, tableName, pascalName));
    actions.push(this.generatePost(table, tableName, pascalName));
    actions.push(this.generatePatch(table, tableName, pascalName));
    actions.push(this.generateDelete(table, tableName, pascalName));

    // Webhook handler
    if (this.options.generateWebhook) {
      actions.push(this.generateWebhook(table, tableName, pascalName));
    }

    const content = `// Generated HTTP actions for ${table.tableName}
// Do not edit this file directly - it will be overwritten
//
// HTTP actions expose REST-like endpoints that can be called
// from any HTTP client. They handle raw requests and responses.
//
// Routes (to be added to http.ts):
// - GET  ${this.options.basePath}/${tableName}     -> ${tableName}HttpActions.list
// - GET  ${this.options.basePath}/${tableName}/:id -> ${tableName}HttpActions.getById
// - POST ${this.options.basePath}/${tableName}     -> ${tableName}HttpActions.create
// - PATCH ${this.options.basePath}/${tableName}/:id -> ${tableName}HttpActions.update
// - DELETE ${this.options.basePath}/${tableName}/:id -> ${tableName}HttpActions.remove
${this.options.generateWebhook ? `// - POST ${this.options.basePath}/${tableName}/webhook -> ${tableName}HttpActions.webhook` : ''}

import { httpAction } from "./_generated/server";
import { api } from "./_generated/api";

${actions.join('\n\n')}
`;

    return { content, count: actions.length };
  }

  /**
   * Generate HTTP route definitions for http.ts
   */
  generateRoutes(tables: TableInfo[]): string {
    const routes: string[] = [];

    for (const table of tables) {
      const tableName = table.tableName;
      routes.push(`  // ${toPascalCase(tableName)} routes`);
      routes.push(`  http.route({`);
      routes.push(`    path: "${this.options.basePath}/${tableName}",`);
      routes.push(`    method: "GET",`);
      routes.push(`    handler: ${tableName}HttpActions.list,`);
      routes.push(`  }),`);
      routes.push(`  http.route({`);
      routes.push(`    path: "${this.options.basePath}/${tableName}/:id",`);
      routes.push(`    method: "GET",`);
      routes.push(`    handler: ${tableName}HttpActions.getById,`);
      routes.push(`  }),`);
      routes.push(`  http.route({`);
      routes.push(`    path: "${this.options.basePath}/${tableName}",`);
      routes.push(`    method: "POST",`);
      routes.push(`    handler: ${tableName}HttpActions.create,`);
      routes.push(`  }),`);
      routes.push(`  http.route({`);
      routes.push(`    path: "${this.options.basePath}/${tableName}/:id",`);
      routes.push(`    method: "PATCH",`);
      routes.push(`    handler: ${tableName}HttpActions.update,`);
      routes.push(`  }),`);
      routes.push(`  http.route({`);
      routes.push(`    path: "${this.options.basePath}/${tableName}/:id",`);
      routes.push(`    method: "DELETE",`);
      routes.push(`    handler: ${tableName}HttpActions.remove,`);
      routes.push(`  }),`);

      if (this.options.generateWebhook) {
        routes.push(`  http.route({`);
        routes.push(
          `    path: "${this.options.basePath}/${tableName}/webhook",`
        );
        routes.push(`    method: "POST",`);
        routes.push(`    handler: ${tableName}HttpActions.webhook,`);
        routes.push(`  }),`);
      }
      routes.push('');
    }

    return routes.join('\n');
  }

  /**
   * Generate helper functions for HTTP actions
   */
  private generateHelpers(): string {
    const corsHeaders = this.options.includeCors
      ? `
/**
 * CORS headers for cross-origin requests
 */
const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, POST, PATCH, DELETE, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type, Authorization",
};`
      : '';

    const authHelper = this.options.includeAuth
      ? `
/**
 * Verify authentication for HTTP actions.
 *
 * IMPORTANT: HTTP actions don't have built-in auth like queries/mutations.
 * You must verify tokens manually.
 *
 * Options for authentication:
 * 1. Use Convex Auth with Clerk/Auth0 - verify JWTs using your provider's SDK
 * 2. API Key authentication - store hashed keys in Convex and verify
 * 3. Session tokens - verify against your session store
 *
 * For production, replace this stub with actual verification logic.
 * See: https://docs.convex.dev/auth
 *
 * @example Clerk Authentication
 * \`\`\`typescript
 * import { verifyToken } from "@clerk/backend";
 *
 * async function verifyAuth(request: Request) {
 *   const authHeader = request.headers.get("Authorization");
 *   if (!authHeader?.startsWith("Bearer ")) {
 *     return { authenticated: false, error: "Missing token" };
 *   }
 *
 *   const token = authHeader.slice(7);
 *   try {
 *     const verified = await verifyToken(token, {
 *       secretKey: process.env.CLERK_SECRET_KEY!,
 *     });
 *     return { authenticated: true, userId: verified.sub };
 *   } catch (error) {
 *     return { authenticated: false, error: "Invalid token" };
 *   }
 * }
 * \`\`\`
 *
 * @example Auth0 Authentication
 * \`\`\`typescript
 * import { jwtVerify, createRemoteJWKSet } from "jose";
 *
 * const JWKS = createRemoteJWKSet(
 *   new URL(\`https://\${process.env.AUTH0_DOMAIN}/.well-known/jwks.json\`)
 * );
 *
 * async function verifyAuth(request: Request) {
 *   const authHeader = request.headers.get("Authorization");
 *   if (!authHeader?.startsWith("Bearer ")) {
 *     return { authenticated: false, error: "Missing token" };
 *   }
 *
 *   const token = authHeader.slice(7);
 *   try {
 *     const { payload } = await jwtVerify(token, JWKS, {
 *       issuer: \`https://\${process.env.AUTH0_DOMAIN}/\`,
 *       audience: process.env.AUTH0_AUDIENCE,
 *     });
 *     return { authenticated: true, userId: payload.sub };
 *   } catch (error) {
 *     return { authenticated: false, error: "Invalid token" };
 *   }
 * }
 * \`\`\`
 *
 * @example API Key Authentication
 * \`\`\`typescript
 * import { api } from "./_generated/api";
 *
 * async function verifyAuth(request: Request) {
 *   const authHeader = request.headers.get("Authorization");
 *   if (!authHeader?.startsWith("ApiKey ")) {
 *     return { authenticated: false, error: "Missing API key" };
 *   }
 *
 *   const apiKey = authHeader.slice(7);
 *   // Hash the provided key and compare with stored hash
 *   const hashedKey = await hashApiKey(apiKey);
 *   const validKey = await ctx.runQuery(api.apiKeys.verifyKey, { hashedKey });
 *
 *   if (!validKey) {
 *     return { authenticated: false, error: "Invalid API key" };
 *   }
 *
 *   return { authenticated: true, userId: validKey.userId };
 * }
 * \`\`\`
 */
async function verifyAuth(request: Request): Promise<{ authenticated: boolean; userId?: string; error?: string }> {
  const authHeader = request.headers.get("Authorization");

  if (!authHeader) {
    return { authenticated: false, error: "Missing Authorization header" };
  }

  // Bearer token (JWT) authentication - Clerk/Auth0/Custom
  if (authHeader.startsWith("Bearer ")) {
    const token = authHeader.slice(7);

    // SECURITY: You MUST implement actual token verification here.
    // See examples above for Clerk and Auth0 implementation.
    //
    // For now, reject all tokens until verification is implemented:
    console.warn("[AUTH] Bearer token verification not implemented - rejecting request");
    return { authenticated: false, error: "Token verification not configured" };

    // After implementing verification, return:
    // return { authenticated: true, userId: verifiedUserId };
  }

  // API key authentication
  if (authHeader.startsWith("ApiKey ")) {
    const apiKey = authHeader.slice(7);

    // SECURITY: Verify API key against hashed keys stored in Convex.
    // Use a timing-safe comparison to prevent timing attacks.
    // Store only hashed API keys, never plaintext.
    // See example above for implementation.
    //
    // For now, reject all API keys until verification is implemented:
    console.warn("[AUTH] API key verification not implemented - rejecting request");
    return { authenticated: false, error: "API key verification not configured" };

    // After implementing verification, return:
    // return { authenticated: true, userId: associatedUserId };
  }

  return { authenticated: false, error: "Unsupported authentication scheme" };
}`
      : '';

    return `// Helper functions for HTTP actions
${corsHeaders}
${authHelper}

/**
 * Create a JSON response with appropriate headers
 */
function jsonResponse(data: unknown, status = 200): Response {
  return new Response(JSON.stringify(data), {
    status,
    headers: {
      "Content-Type": "application/json",
      ${this.options.includeCors ? '...corsHeaders,' : ''}
    },
  });
}

/**
 * Create an error response
 */
function errorResponse(message: string, status = 400): Response {
  return jsonResponse({ error: message }, status);
}

/**
 * Extract ID from URL path
 * Handles paths like /api/tableName/id123
 */
function extractIdFromPath(url: URL, basePath: string): string | null {
  const path = url.pathname;
  const parts = path.split("/").filter(Boolean);
  // Path format: api / tableName / id
  if (parts.length >= 3) {
    return parts[parts.length - 1];
  }
  return null;
}`;
  }

  /**
   * Generate GET list endpoint
   */
  private generateGetList(
    table: TableInfo,
    tableName: string,
    pascalName: string
  ): string {
    return `/**
 * GET ${this.options.basePath}/${tableName}
 * List all ${pascalName} documents with optional pagination
 */
export const list = httpAction(async (ctx, request) => {
  // Handle CORS preflight
  if (request.method === "OPTIONS") {
    return new Response(null, { status: 204, headers: corsHeaders });
  }

  ${
    this.options.includeAuth
      ? `// Verify authentication
  const auth = await verifyAuth(request);
  if (!auth.authenticated) {
    return errorResponse("Unauthorized", 401);
  }`
      : ''
  }

  try {
    // Parse query parameters
    const url = new URL(request.url);
    const numItems = parseInt(url.searchParams.get("limit") ?? "50");
    const cursor = url.searchParams.get("cursor") ?? null;

    // Fetch documents using Convex pagination
    const result = await ctx.runQuery(api.${tableName}.list, {
      paginationOpts: { numItems, cursor },
    });

    return jsonResponse({
      data: result.page,
      pagination: {
        hasMore: !result.isDone,
        nextCursor: result.continueCursor,
      },
    });
  } catch (error) {
    console.error("Error listing ${tableName}:", error);
    return errorResponse(
      error instanceof Error ? error.message : "Internal server error",
      500
    );
  }
});`;
  }

  /**
   * Generate GET by ID endpoint
   */
  private generateGetById(
    table: TableInfo,
    tableName: string,
    pascalName: string
  ): string {
    return `/**
 * GET ${this.options.basePath}/${tableName}/:id
 * Get a single ${pascalName} by ID
 */
export const getById = httpAction(async (ctx, request) => {
  // Handle CORS preflight
  if (request.method === "OPTIONS") {
    return new Response(null, { status: 204, headers: corsHeaders });
  }

  ${
    this.options.includeAuth
      ? `// Verify authentication
  const auth = await verifyAuth(request);
  if (!auth.authenticated) {
    return errorResponse("Unauthorized", 401);
  }`
      : ''
  }

  try {
    // Extract ID from URL
    const url = new URL(request.url);
    const id = extractIdFromPath(url, "${this.options.basePath}/${tableName}");

    if (!id) {
      return errorResponse("Missing document ID", 400);
    }

    // Fetch document
    const doc = await ctx.runQuery(api.${tableName}.get, { id: id as any });

    if (!doc) {
      return errorResponse("${pascalName} not found", 404);
    }

    return jsonResponse({ data: doc });
  } catch (error) {
    console.error("Error fetching ${tableName}:", error);
    return errorResponse(
      error instanceof Error ? error.message : "Internal server error",
      500
    );
  }
});`;
  }

  /**
   * Generate POST (create) endpoint
   */
  private generatePost(
    table: TableInfo,
    tableName: string,
    pascalName: string
  ): string {
    return `/**
 * POST ${this.options.basePath}/${tableName}
 * Create a new ${pascalName}
 */
export const create = httpAction(async (ctx, request) => {
  // Handle CORS preflight
  if (request.method === "OPTIONS") {
    return new Response(null, { status: 204, headers: corsHeaders });
  }

  ${
    this.options.includeAuth
      ? `// Verify authentication
  const auth = await verifyAuth(request);
  if (!auth.authenticated) {
    return errorResponse("Unauthorized", 401);
  }`
      : ''
  }

  try {
    // Parse request body
    const body = await request.json();

    if (!body || typeof body !== "object") {
      return errorResponse("Invalid request body", 400);
    }

    // Create document
    const id = await ctx.runMutation(api.${tableName}.create, body);

    return jsonResponse(
      {
        data: { id },
        message: "${pascalName} created successfully",
      },
      201
    );
  } catch (error) {
    console.error("Error creating ${tableName}:", error);

    // Handle validation errors
    if (error instanceof Error && error.message.includes("validation")) {
      return errorResponse(error.message, 400);
    }

    return errorResponse(
      error instanceof Error ? error.message : "Internal server error",
      500
    );
  }
});`;
  }

  /**
   * Generate PATCH (update) endpoint
   */
  private generatePatch(
    table: TableInfo,
    tableName: string,
    pascalName: string
  ): string {
    return `/**
 * PATCH ${this.options.basePath}/${tableName}/:id
 * Update an existing ${pascalName}
 */
export const update = httpAction(async (ctx, request) => {
  // Handle CORS preflight
  if (request.method === "OPTIONS") {
    return new Response(null, { status: 204, headers: corsHeaders });
  }

  ${
    this.options.includeAuth
      ? `// Verify authentication
  const auth = await verifyAuth(request);
  if (!auth.authenticated) {
    return errorResponse("Unauthorized", 401);
  }`
      : ''
  }

  try {
    // Extract ID from URL
    const url = new URL(request.url);
    const id = extractIdFromPath(url, "${this.options.basePath}/${tableName}");

    if (!id) {
      return errorResponse("Missing document ID", 400);
    }

    // Parse request body
    const body = await request.json();

    if (!body || typeof body !== "object") {
      return errorResponse("Invalid request body", 400);
    }

    // Update document
    await ctx.runMutation(api.${tableName}.update, {
      id: id as any,
      ...body,
    });

    return jsonResponse({
      data: { id },
      message: "${pascalName} updated successfully",
    });
  } catch (error) {
    console.error("Error updating ${tableName}:", error);

    // Handle not found
    if (error instanceof Error && error.message.includes("not found")) {
      return errorResponse("${pascalName} not found", 404);
    }

    return errorResponse(
      error instanceof Error ? error.message : "Internal server error",
      500
    );
  }
});`;
  }

  /**
   * Generate DELETE endpoint
   */
  private generateDelete(
    table: TableInfo,
    tableName: string,
    pascalName: string
  ): string {
    return `/**
 * DELETE ${this.options.basePath}/${tableName}/:id
 * Delete a ${pascalName}
 */
export const remove = httpAction(async (ctx, request) => {
  // Handle CORS preflight
  if (request.method === "OPTIONS") {
    return new Response(null, { status: 204, headers: corsHeaders });
  }

  ${
    this.options.includeAuth
      ? `// Verify authentication
  const auth = await verifyAuth(request);
  if (!auth.authenticated) {
    return errorResponse("Unauthorized", 401);
  }`
      : ''
  }

  try {
    // Extract ID from URL
    const url = new URL(request.url);
    const id = extractIdFromPath(url, "${this.options.basePath}/${tableName}");

    if (!id) {
      return errorResponse("Missing document ID", 400);
    }

    // Delete document
    await ctx.runMutation(api.${tableName}.remove, { id: id as any });

    return jsonResponse({
      data: { id },
      message: "${pascalName} deleted successfully",
    });
  } catch (error) {
    console.error("Error deleting ${tableName}:", error);

    // Handle not found
    if (error instanceof Error && error.message.includes("not found")) {
      return errorResponse("${pascalName} not found", 404);
    }

    return errorResponse(
      error instanceof Error ? error.message : "Internal server error",
      500
    );
  }
});`;
  }

  /**
   * Generate webhook handler endpoint
   */
  private generateWebhook(
    table: TableInfo,
    tableName: string,
    pascalName: string
  ): string {
    return `/**
 * POST ${this.options.basePath}/${tableName}/webhook
 * Handle webhook events for ${pascalName}
 *
 * Common webhook sources:
 * - Stripe (payments)
 * - GitHub (repository events)
 * - Twilio (SMS/voice)
 * - SendGrid (email events)
 * - Custom integrations
 */
export const webhook = httpAction(async (ctx, request) => {
  try {
    // 1. Verify webhook signature (customize based on provider)
    const signature = request.headers.get("x-webhook-signature");
    const webhookSecret = process.env.WEBHOOK_SECRET;

    if (webhookSecret && signature) {
      // Example: Verify HMAC signature
      // const isValid = await verifyWebhookSignature(request, signature, webhookSecret);
      // if (!isValid) {
      //   return errorResponse("Invalid webhook signature", 401);
      // }
    }

    // 2. Parse webhook payload
    const contentType = request.headers.get("content-type") ?? "";
    let payload: unknown;

    if (contentType.includes("application/json")) {
      payload = await request.json();
    } else if (contentType.includes("application/x-www-form-urlencoded")) {
      const text = await request.text();
      payload = Object.fromEntries(new URLSearchParams(text));
    } else {
      payload = await request.text();
    }

    // 3. Extract event type (customize based on provider)
    const eventType =
      (payload as Record<string, any>)?.type ??
      (payload as Record<string, any>)?.event ??
      (payload as Record<string, any>)?.action ??
      "unknown";

    console.log(\`Received webhook event: \${eventType}\`, { payload });

    // 4. Handle different event types
    switch (eventType) {
      case "created":
      case "${tableName}.created":
        // Handle creation event
        // await ctx.runMutation(api.${tableName}.create, transformPayload(payload));
        break;

      case "updated":
      case "${tableName}.updated":
        // Handle update event
        // await ctx.runMutation(api.${tableName}.update, transformPayload(payload));
        break;

      case "deleted":
      case "${tableName}.deleted":
        // Handle deletion event
        // await ctx.runMutation(api.${tableName}.remove, { id: payload.id });
        break;

      default:
        console.log(\`Unhandled webhook event type: \${eventType}\`);
    }

    // 5. Return success response
    // Most webhook providers expect a 200 status to confirm receipt
    return jsonResponse({
      received: true,
      eventType,
      timestamp: Date.now(),
    });
  } catch (error) {
    console.error("Webhook error:", error);

    // Return 200 to prevent retries for non-retryable errors
    // Return 500 for retryable errors (depends on your use case)
    return jsonResponse(
      {
        received: true,
        error: error instanceof Error ? error.message : "Processing error",
      },
      200
    );
  }
});`;
  }

  /**
   * Generate the main http.ts file content
   */
  generateHttpFile(tables: TableInfo[]): string {
    const imports = tables
      .map(
        (t) =>
          `import * as ${t.tableName}HttpActions from "./${t.tableName}/http-actions";`
      )
      .join('\n');

    const routes = this.generateRoutes(tables);

    return `// Generated Convex HTTP routes
// Do not edit this file directly - it will be overwritten
//
// This file defines all HTTP endpoints for your Convex application.
// HTTP actions provide REST-like endpoints that can be called from
// any HTTP client.

import { httpRouter } from "convex/server";

${imports}

const http = httpRouter();

/**
 * Define HTTP routes
 * Each route maps a path and method to an HTTP action handler
 */
${routes}

// Export the router
export default http;
`;
  }

}
