/**
 * Convex Mutation Generator
 *
 * Generates mutation functions for Convex:
 * - create: Create a single document
 * - update: Update a document by ID
 * - remove: Delete a document by ID
 * - batchCreate: Create multiple documents
 * - batchRemove: Delete multiple documents
 * - upsert: Create or update based on unique field
 *
 * Supports Convex API versions:
 * - 1.30: Uses old API style (db.patch(docId, updates))
 * - 1.31+: Uses new API style (db.patch("tableName", docId, updates))
 */

import type {
  TableInfo,
  ColumnInfo,
} from '../../introspector/schema-introspector.js';
import type {
  MutationGeneratorResult,
  ConvexApiVersion,
} from '../../convex/types.js';

/**
 * Options for the mutation generator
 */
export interface MutationGeneratorOptions {
  /**
   * Convex API version to target
   * - '1.30': Old API style (db.patch(docId, updates))
   * - '1.31': New API style (db.patch("tableName", docId, updates))
   * Default: '1.30' for backwards compatibility
   */
  convexApiVersion?: ConvexApiVersion;
}

/**
 * Generates Convex mutation functions
 */
export class MutationGenerator {
  private options: MutationGeneratorOptions;

  constructor(options: MutationGeneratorOptions = {}) {
    this.options = {
      convexApiVersion: '1.30',
      ...options,
    };
  }

  /**
   * Check if using Convex 1.31+ API style
   */
  private useNewApiStyle(): boolean {
    return this.options.convexApiVersion === '1.31';
  }
  /**
   * Generate all mutations for a table
   */
  generate(table: TableInfo): MutationGeneratorResult {
    const tableName = table.tableName;
    const pascalName = this.toPascalCase(tableName);

    const mutations: string[] = [];

    // 1. create - Create single document
    mutations.push(this.generateCreate(table, tableName, pascalName));

    // 2. update - Update single document
    mutations.push(this.generateUpdate(table, tableName, pascalName));

    // 3. remove - Delete single document
    mutations.push(this.generateRemove(tableName, pascalName));

    // 4. batchCreate - Create multiple documents
    mutations.push(this.generateBatchCreate(table, tableName, pascalName));

    // 5. batchRemove - Delete multiple documents
    mutations.push(this.generateBatchRemove(tableName, pascalName));

    // 6. upsert - Create or update based on unique field
    const uniqueField = this.findUniqueField(table);
    if (uniqueField) {
      mutations.push(
        this.generateUpsert(table, tableName, pascalName, uniqueField)
      );
    }

    const content = `// Generated mutations for ${table.tableName}
// Do not edit this file directly - it will be overwritten

import { mutation } from "./_generated/server";
import { v } from "convex/values";

${mutations.join('\n\n')}
`;

    return { content, count: mutations.length };
  }

  /**
   * Generate create mutation
   */
  private generateCreate(
    table: TableInfo,
    tableName: string,
    pascalName: string
  ): string {
    const createFields = this.getCreateFields(table);
    const argsDefinition = createFields
      .map((col) => {
        const fieldName = this.toCamelCase(col.columnName);
        const validator = this.getConvexValidator(col, table);
        return `    ${fieldName}: ${validator}`;
      })
      .join(',\n');

    const insertFields = createFields
      .map((col) => {
        const fieldName = this.toCamelCase(col.columnName);
        return `      ${fieldName}: args.${fieldName}`;
      })
      .join(',\n');

    return `/**
 * Create a new ${pascalName}
 */
export const create = mutation({
  args: {
${argsDefinition},
  },
  handler: async (ctx, args) => {
    const id = await ctx.db.insert("${tableName}", {
${insertFields},
    });
    return id;
  },
});`;
  }

  /**
   * Generate update mutation
   */
  private generateUpdate(
    table: TableInfo,
    tableName: string,
    pascalName: string
  ): string {
    const updateFields = this.getUpdateFields(table);
    const argsDefinition = updateFields
      .map((col) => {
        const fieldName = this.toCamelCase(col.columnName);
        let validator = this.getConvexValidator(col, table);
        // Make all update fields optional
        if (!validator.startsWith('v.optional(')) {
          validator = `v.optional(${validator})`;
        }
        return `    ${fieldName}: ${validator}`;
      })
      .join(',\n');

    // Convex 1.31+ requires table name as first parameter
    const patchCall = this.useNewApiStyle()
      ? `ctx.db.patch("${tableName}", id, cleanUpdates)`
      : `ctx.db.patch(id, cleanUpdates)`;

    return `/**
 * Update an existing ${pascalName}
 */
export const update = mutation({
  args: {
    id: v.id("${tableName}"),
${argsDefinition},
  },
  handler: async (ctx, args) => {
    const { id, ...updates } = args;

    // Remove undefined values
    const cleanUpdates = Object.fromEntries(
      Object.entries(updates).filter(([_, v]) => v !== undefined)
    );

    if (Object.keys(cleanUpdates).length === 0) {
      return id;
    }

    await ${patchCall};
    return id;
  },
});`;
  }

  /**
   * Generate remove mutation
   */
  private generateRemove(tableName: string, pascalName: string): string {
    // Convex 1.31+ requires table name as first parameter
    const deleteCall = this.useNewApiStyle()
      ? `ctx.db.delete("${tableName}", args.id)`
      : `ctx.db.delete(args.id)`;

    return `/**
 * Delete a ${pascalName}
 */
export const remove = mutation({
  args: {
    id: v.id("${tableName}"),
  },
  handler: async (ctx, args) => {
    await ${deleteCall};
    return args.id;
  },
});`;
  }

  /**
   * Generate batch create mutation
   */
  private generateBatchCreate(
    table: TableInfo,
    tableName: string,
    pascalName: string
  ): string {
    const createFields = this.getCreateFields(table);
    const itemValidator = createFields
      .map((col) => {
        const fieldName = this.toCamelCase(col.columnName);
        const validator = this.getConvexValidator(col, table);
        return `      ${fieldName}: ${validator}`;
      })
      .join(',\n');

    return `/**
 * Create multiple ${pascalName} documents in batch
 */
export const batchCreate = mutation({
  args: {
    items: v.array(v.object({
${itemValidator},
    })),
  },
  handler: async (ctx, args) => {
    const ids = [];

    for (const item of args.items) {
      const id = await ctx.db.insert("${tableName}", item);
      ids.push(id);
    }

    return ids;
  },
});`;
  }

  /**
   * Generate batch remove mutation
   */
  private generateBatchRemove(tableName: string, pascalName: string): string {
    // Convex 1.31+ requires table name as first parameter
    const deleteCall = this.useNewApiStyle()
      ? `ctx.db.delete("${tableName}", id)`
      : `ctx.db.delete(id)`;

    return `/**
 * Delete multiple ${pascalName} documents in batch
 */
export const batchRemove = mutation({
  args: {
    ids: v.array(v.id("${tableName}")),
  },
  handler: async (ctx, args) => {
    for (const id of args.ids) {
      await ${deleteCall};
    }
    return args.ids;
  },
});`;
  }

  /**
   * Generate upsert mutation
   */
  private generateUpsert(
    table: TableInfo,
    tableName: string,
    pascalName: string,
    uniqueField: ColumnInfo
  ): string {
    const fieldName = this.toCamelCase(uniqueField.columnName);
    const indexName = `by_${fieldName}`;
    const createFields = this.getCreateFields(table);

    const argsDefinition = createFields
      .map((col) => {
        const fn = this.toCamelCase(col.columnName);
        const validator = this.getConvexValidator(col, table);
        return `    ${fn}: ${validator}`;
      })
      .join(',\n');

    // Convex 1.31+ requires table name as first parameter
    const patchCall = this.useNewApiStyle()
      ? `ctx.db.patch("${tableName}", existing._id, args)`
      : `ctx.db.patch(existing._id, args)`;

    return `/**
 * Create or update a ${pascalName} based on ${fieldName}
 */
export const upsert = mutation({
  args: {
${argsDefinition},
  },
  handler: async (ctx, args) => {
    const existing = await ctx.db
      .query("${tableName}")
      .withIndex("${indexName}", (q) => q.eq("${fieldName}", args.${fieldName}))
      .unique();

    if (existing) {
      await ${patchCall};
      return existing._id;
    } else {
      return await ctx.db.insert("${tableName}", args);
    }
  },
});`;
  }

  /**
   * Get fields for create operation (exclude auto-generated)
   */
  private getCreateFields(table: TableInfo): ColumnInfo[] {
    return table.columns.filter((col) => {
      // Skip auto-increment/identity columns
      if (col.isIdentity) return false;
      // Skip serial columns
      if (col.columnDefault?.includes('nextval')) return false;
      // Skip primary key columns named 'id'
      if (col.isPrimaryKey && col.columnName.toLowerCase() === 'id')
        return false;
      return true;
    });
  }

  /**
   * Get fields for update operation
   */
  private getUpdateFields(table: TableInfo): ColumnInfo[] {
    return table.columns.filter((col) => {
      // Skip primary keys
      if (col.isPrimaryKey) return false;
      // Skip identity columns
      if (col.isIdentity) return false;
      return true;
    });
  }

  /**
   * Find a unique field for upsert
   */
  private findUniqueField(table: TableInfo): ColumnInfo | null {
    const uniqueIndex = table.indexes.find(
      (idx) =>
        idx.isUnique &&
        !table.primaryKeys.includes(idx.columnName) &&
        !idx.indexName.endsWith('_pkey')
    );

    if (uniqueIndex) {
      return (
        table.columns.find((c) => c.columnName === uniqueIndex.columnName) ||
        null
      );
    }

    return null;
  }

  /**
   * Get Convex validator for a column
   */
  private getConvexValidator(column: ColumnInfo, table: TableInfo): string {
    // Handle foreign keys
    if (column.isForeignKey && column.foreignKeyTable) {
      const base = `v.id("${column.foreignKeyTable}")`;
      return column.isNullable || column.columnDefault
        ? `v.optional(${base})`
        : base;
    }

    const baseType = this.mapToConvexType(column);
    return column.isNullable || column.columnDefault
      ? `v.optional(${baseType})`
      : baseType;
  }

  /**
   * Map PostgreSQL type to Convex validator
   */
  private mapToConvexType(column: ColumnInfo): string {
    const cleanType = column.dataType.split('(')[0].toLowerCase();

    const mapping: Record<string, string> = {
      text: 'v.string()',
      varchar: 'v.string()',
      'character varying': 'v.string()',
      uuid: 'v.string()',
      integer: 'v.number()',
      int: 'v.number()',
      smallint: 'v.number()',
      bigint: 'v.number()',
      decimal: 'v.number()',
      numeric: 'v.number()',
      real: 'v.number()',
      float: 'v.number()',
      'double precision': 'v.number()',
      boolean: 'v.boolean()',
      bool: 'v.boolean()',
      timestamp: 'v.number()',
      timestamptz: 'v.number()',
      'timestamp with time zone': 'v.number()',
      'timestamp without time zone': 'v.number()',
      date: 'v.number()',
      json: 'v.any()',
      jsonb: 'v.any()',
      bytea: 'v.bytes()',
    };

    return mapping[cleanType] || 'v.string()';
  }

  /**
   * Convert snake_case to camelCase
   */
  private toCamelCase(str: string): string {
    return str.replace(/_([a-z])/g, (_, letter) => letter.toUpperCase());
  }

  /**
   * Convert to PascalCase
   */
  private toPascalCase(str: string): string {
    const camel = this.toCamelCase(str);
    return camel.charAt(0).toUpperCase() + camel.slice(1);
  }
}
