/**
 * Convex Mutation Generator
 *
 * Generates mutation functions for Convex:
 * - create: Create a single document
 * - update: Update a document by ID
 * - remove: Delete a document by ID
 * - batchCreate: Create multiple documents
 * - batchRemove: Delete multiple documents
 * - upsert: Create or update based on unique field
 *
 * Supports Convex API versions:
 * - 1.30: Uses old API style (db.patch(docId, updates))
 * - 1.31+: Uses new API style (db.patch("tableName", docId, updates))
 */

import type {
  TableInfo,
  ColumnInfo,
} from '../../introspector/schema-introspector.js';
import type {
  MutationGeneratorResult,
  ConvexApiVersion,
} from '../../convex/types.js';
import {
  toCamelCase,
  toPascalCase,
  escapeFieldName,
} from '../../utils/naming.js';
import { BaseConvexGenerator } from './base-convex-generator.js';

/**
 * Options for the mutation generator
 */
export interface MutationGeneratorOptions {
  /**
   * Convex API version to target
   * - '1.30': Old API style (db.patch(docId, updates))
   * - '1.31': New API style (db.patch("tableName", docId, updates))
   * Default: '1.30' for backwards compatibility
   */
  convexApiVersion?: ConvexApiVersion;
}

const DEFAULT_OPTIONS: MutationGeneratorOptions = {
  convexApiVersion: '1.30',
};

/**
 * Generates Convex mutation functions
 */
export class MutationGenerator extends BaseConvexGenerator<MutationGeneratorOptions> {
  constructor(options: MutationGeneratorOptions = {}) {
    super(DEFAULT_OPTIONS, options);
  }
  /**
   * Generate all mutations for a table
   */
  generate(table: TableInfo): MutationGeneratorResult {
    const tableName = table.tableName;
    const pascalName = toPascalCase(tableName);

    const mutations: string[] = [];

    // 1. create - Create single document
    mutations.push(this.generateCreate(table, tableName, pascalName));

    // 2. update - Update single document
    mutations.push(this.generateUpdate(table, tableName, pascalName));

    // 3. remove - Delete single document
    mutations.push(this.generateRemove(tableName, pascalName));

    // 4. batchCreate - Create multiple documents
    mutations.push(this.generateBatchCreate(table, tableName, pascalName));

    // 5. batchRemove - Delete multiple documents
    mutations.push(this.generateBatchRemove(tableName, pascalName));

    // 6. upsert - Create or update based on unique field
    const uniqueField = this.findUniqueField(table);
    if (uniqueField) {
      mutations.push(
        this.generateUpsert(table, tableName, pascalName, uniqueField)
      );
    }

    const content = `// Generated mutations for ${table.tableName}
// Do not edit this file directly - it will be overwritten
//
// AUTHENTICATION: To require auth, add to any handler:
//   const identity = await ctx.auth.getUserIdentity();
//   if (!identity) throw new Error("Unauthenticated");
// See: https://docs.convex.dev/auth

import { mutation } from "./_generated/server";
import { v } from "convex/values";

${mutations.join('\n\n')}
`;

    return { content, count: mutations.length };
  }

  /**
   * Generate create mutation
   */
  private generateCreate(
    table: TableInfo,
    tableName: string,
    pascalName: string
  ): string {
    const createFields = this.getCreateFields(table);
    const argsDefinition = createFields
      .map((col) => {
        const fieldName = escapeFieldName(toCamelCase(col.columnName));
        const validator = this.getConvexValidator(col);
        return `    ${fieldName}: ${validator}`;
      })
      .join(',\n');

    const insertFields = createFields
      .map((col) => {
        const fieldName = escapeFieldName(toCamelCase(col.columnName));
        return `      ${fieldName}: args.${fieldName}`;
      })
      .join(',\n');

    return `/**
 * Create a new ${pascalName}
 *
 * @example
 * \`\`\`typescript
 * // React usage:
 * import { useMutation } from "convex/react";
 * import { api } from "./_generated/api";
 *
 * function Create${pascalName}Form() {
 *   const create${pascalName} = useMutation(api.${tableName}.create);
 *
 *   const handleSubmit = async (formData) => {
 *     const id = await create${pascalName}(formData);
 *     console.log("Created with ID:", id);
 *   };
 *
 *   return <form onSubmit={handleSubmit}>...</form>;
 * }
 * \`\`\`
 *
 * @returns The ID of the newly created ${pascalName} document
 */
export const create = mutation({
  args: {
${argsDefinition},
  },
  handler: async (ctx, args): Promise<Id<"${tableName}">> => {
    const id = await ctx.db.insert("${tableName}", {
${insertFields},
    });
    return id;
  },
});`;
  }

  /**
   * Generate update mutation
   */
  private generateUpdate(
    table: TableInfo,
    tableName: string,
    pascalName: string
  ): string {
    const updateFields = this.getUpdateFields(table);
    const argsDefinition = updateFields
      .map((col) => {
        const fieldName = escapeFieldName(toCamelCase(col.columnName));
        let validator = this.getConvexValidator(col);
        // Make all update fields optional
        if (!validator.startsWith('v.optional(')) {
          validator = `v.optional(${validator})`;
        }
        return `    ${fieldName}: ${validator}`;
      })
      .join(',\n');

    // Convex 1.31+ requires table name as first parameter
    const patchCall = this.useNewApiStyle()
      ? `ctx.db.patch("${tableName}", id, cleanUpdates)`
      : `ctx.db.patch(id, cleanUpdates)`;

    return `/**
 * Update an existing ${pascalName}
 *
 * All fields are optional. Only provided fields will be updated.
 *
 * @example
 * \`\`\`typescript
 * // React usage:
 * import { useMutation } from "convex/react";
 * import { api } from "./_generated/api";
 *
 * function Edit${pascalName}({ id }: { id: Id<"${tableName}"> }) {
 *   const update${pascalName} = useMutation(api.${tableName}.update);
 *
 *   const handleUpdate = async (updates) => {
 *     await update${pascalName}({ id, ...updates });
 *   };
 *
 *   return <button onClick={() => handleUpdate({ name: "New Name" })}>Update</button>;
 * }
 * \`\`\`
 *
 * @param args.id - The document ID to update
 * @returns The ID of the updated ${pascalName} document
 */
export const update = mutation({
  args: {
    id: v.id("${tableName}"),
${argsDefinition},
  },
  handler: async (ctx, args): Promise<Id<"${tableName}">> => {
    const { id, ...updates } = args;

    // Remove undefined values
    const cleanUpdates = Object.fromEntries(
      Object.entries(updates).filter(([_, v]) => v !== undefined)
    );

    if (Object.keys(cleanUpdates).length === 0) {
      return id;
    }

    await ${patchCall};
    return id;
  },
});`;
  }

  /**
   * Generate remove mutation
   */
  private generateRemove(tableName: string, pascalName: string): string {
    // Convex 1.31+ requires table name as first parameter
    const deleteCall = this.useNewApiStyle()
      ? `ctx.db.delete("${tableName}", args.id)`
      : `ctx.db.delete(args.id)`;

    return `/**
 * Delete a ${pascalName}
 *
 * @example
 * \`\`\`typescript
 * // React usage:
 * import { useMutation } from "convex/react";
 * import { api } from "./_generated/api";
 *
 * function Delete${pascalName}Button({ id }: { id: Id<"${tableName}"> }) {
 *   const remove${pascalName} = useMutation(api.${tableName}.remove);
 *
 *   const handleDelete = async () => {
 *     await remove${pascalName}({ id });
 *     console.log("Deleted successfully");
 *   };
 *
 *   return <button onClick={handleDelete}>Delete</button>;
 * }
 * \`\`\`
 *
 * @param args.id - The document ID to delete
 * @returns The ID of the deleted ${pascalName} document
 */
export const remove = mutation({
  args: {
    id: v.id("${tableName}"),
  },
  handler: async (ctx, args): Promise<Id<"${tableName}">> => {
    await ${deleteCall};
    return args.id;
  },
});`;
  }

  /**
   * Generate batch create mutation
   */
  private generateBatchCreate(
    table: TableInfo,
    tableName: string,
    pascalName: string
  ): string {
    const createFields = this.getCreateFields(table);
    const itemValidator = createFields
      .map((col) => {
        const fieldName = escapeFieldName(toCamelCase(col.columnName));
        const validator = this.getConvexValidator(col);
        return `      ${fieldName}: ${validator}`;
      })
      .join(',\n');

    return `/**
 * Create multiple ${pascalName} documents in batch
 *
 * Automatically chunks large batches to prevent timeout issues.
 * For batches >1000 items, consider using scheduler for background processing.
 *
 * @example
 * \`\`\`typescript
 * // React usage:
 * import { useMutation } from "convex/react";
 * import { api } from "./_generated/api";
 *
 * function Bulk${pascalName}Import({ data }: { data: Array<any> }) {
 *   const batchCreate = useMutation(api.${tableName}.batchCreate);
 *
 *   const handleImport = async () => {
 *     const ids = await batchCreate({ items: data });
 *     console.log(\`Created \${ids.length} ${pascalName}s\`);
 *   };
 *
 *   return <button onClick={handleImport}>Import {data.length} items</button>;
 * }
 * \`\`\`
 *
 * @param args.items - Array of ${pascalName} objects to create
 * @returns Array of IDs for the created documents
 */
export const batchCreate = mutation({
  args: {
    items: v.array(v.object({
${itemValidator},
    })),
  },
  handler: async (ctx, args): Promise<Array<Id<"${tableName}">>> => {
    const ids: Array<Id<"${tableName}">> = [];
    const CHUNK_SIZE = 100; // Process in chunks to avoid timeout

    // Process in chunks for large batches (>1000 items)
    for (let i = 0; i < args.items.length; i += CHUNK_SIZE) {
      const chunk = args.items.slice(i, i + CHUNK_SIZE);

      for (const item of chunk) {
        const id = await ctx.db.insert("${tableName}", item);
        ids.push(id);
      }

    }

    return ids;
  },
});`;
  }

  /**
   * Generate batch remove mutation
   */
  private generateBatchRemove(tableName: string, pascalName: string): string {
    // Convex 1.31+ requires table name as first parameter
    const deleteCall = this.useNewApiStyle()
      ? `ctx.db.delete("${tableName}", id)`
      : `ctx.db.delete(id)`;

    return `/**
 * Delete multiple ${pascalName} documents in batch
 *
 * Automatically chunks large batches to prevent timeout issues.
 * For batches >1000 items, consider using scheduler for background processing.
 *
 * @example
 * \`\`\`typescript
 * // React usage:
 * import { useMutation } from "convex/react";
 * import { api } from "./_generated/api";
 *
 * function BulkDelete${pascalName}({ ids }: { ids: Array<Id<"${tableName}">> }) {
 *   const batchRemove = useMutation(api.${tableName}.batchRemove);
 *
 *   const handleDelete = async () => {
 *     await batchRemove({ ids });
 *     console.log(\`Deleted \${ids.length} ${pascalName}s\`);
 *   };
 *
 *   return <button onClick={handleDelete}>Delete {ids.length} items</button>;
 * }
 * \`\`\`
 *
 * @param args.ids - Array of document IDs to delete
 * @returns Array of deleted document IDs
 */
export const batchRemove = mutation({
  args: {
    ids: v.array(v.id("${tableName}")),
  },
  handler: async (ctx, args): Promise<Array<Id<"${tableName}">>> => {
    const CHUNK_SIZE = 100; // Process in chunks to avoid timeout

    // Process in chunks for large batches (>1000 items)
    for (let i = 0; i < args.ids.length; i += CHUNK_SIZE) {
      const chunk = args.ids.slice(i, i + CHUNK_SIZE);

      for (const id of chunk) {
        await ${deleteCall};
      }

    }

    return args.ids;
  },
});`;
  }

  /**
   * Generate upsert mutation
   */
  private generateUpsert(
    table: TableInfo,
    tableName: string,
    pascalName: string,
    uniqueField: ColumnInfo
  ): string {
    const fieldName = escapeFieldName(toCamelCase(uniqueField.columnName));
    const indexName = `by_${fieldName}`;
    const createFields = this.getCreateFields(table);

    const argsDefinition = createFields
      .map((col) => {
        const fn = escapeFieldName(toCamelCase(col.columnName));
        const validator = this.getConvexValidator(col);
        return `    ${fn}: ${validator}`;
      })
      .join(',\n');

    // Convex 1.31+ requires table name as first parameter
    const patchCall = this.useNewApiStyle()
      ? `ctx.db.patch("${tableName}", existing._id, args)`
      : `ctx.db.patch(existing._id, args)`;

    return `/**
 * Create or update a ${pascalName} based on ${fieldName}
 *
 * If a document with the given ${fieldName} exists, it will be updated.
 * Otherwise, a new document will be created.
 *
 * @example
 * \`\`\`typescript
 * // React usage:
 * import { useMutation } from "convex/react";
 * import { api } from "./_generated/api";
 *
 * function Upsert${pascalName}({ ${fieldName}, data }: { ${fieldName}: string, data: Record<string, unknown> }) {
 *   const upsert${pascalName} = useMutation(api.${tableName}.upsert);
 *
 *   const handleUpsert = async () => {
 *     const id = await upsert${pascalName}({ ${fieldName}, ...data });
 *     console.log("Upserted with ID:", id);
 *   };
 *
 *   return <button onClick={handleUpsert}>Save</button>;
 * }
 * \`\`\`
 *
 * @param args.${fieldName} - The unique ${fieldName} to check for existing document
 * @returns The ID of the created or updated ${pascalName} document
 */
export const upsert = mutation({
  args: {
${argsDefinition},
  },
  handler: async (ctx, args): Promise<Id<"${tableName}">> => {
    const existing = await ctx.db
      .query("${tableName}")
      .withIndex("${indexName}", (q) => q.eq("${fieldName}", args.${fieldName}))
      .unique();

    if (existing) {
      await ${patchCall};
      return existing._id;
    }

    return await ctx.db.insert("${tableName}", args);
  },
});`;
  }

  /**
   * Find a unique field for upsert
   */
  private findUniqueField(table: TableInfo): ColumnInfo | null {
    const uniqueIndex = table.indexes.find(
      (idx) =>
        idx.isUnique &&
        !table.primaryKeys.includes(idx.columnName) &&
        !idx.indexName.endsWith('_pkey')
    );

    if (uniqueIndex) {
      return (
        table.columns.find((c) => c.columnName === uniqueIndex.columnName) ||
        null
      );
    }

    return null;
  }
}
