/**
 * Convex Query Generator
 *
 * Generates query functions for Convex:
 * - get: Get single document by ID
 * - list: List all documents with pagination
 * - getBy[Field]: Get by indexed fields
 * - search: Full-text search (if text fields exist)
 * - count: Count all documents
 *
 * Supports Convex API versions:
 * - 1.30: Uses old API style (db.get(docId))
 * - 1.31+: Uses new API style (db.get("tableName", docId))
 */

import type {
  TableInfo,
  ColumnInfo,
} from '../../introspector/schema-introspector.js';
import type {
  QueryGeneratorResult,
  ConvexApiVersion,
} from '../../convex/types.js';

/**
 * Options for the query generator
 */
export interface QueryGeneratorOptions {
  /**
   * Convex API version to target
   * - '1.30': Old API style (db.get(docId))
   * - '1.31': New API style (db.get("tableName", docId))
   * Default: '1.30' for backwards compatibility
   */
  convexApiVersion?: ConvexApiVersion;
}

/**
 * Generates Convex query functions
 */
export class QueryGenerator {
  private options: QueryGeneratorOptions;

  constructor(options: QueryGeneratorOptions = {}) {
    this.options = {
      convexApiVersion: '1.30',
      ...options,
    };
  }

  /**
   * Check if using Convex 1.31+ API style
   */
  private useNewApiStyle(): boolean {
    return this.options.convexApiVersion === '1.31';
  }
  /**
   * Generate all queries for a table
   */
  generate(table: TableInfo): QueryGeneratorResult {
    const tableName = table.tableName;
    const pascalName = this.toPascalCase(tableName);

    const queries: string[] = [];

    // 1. get - Get single document by ID
    queries.push(this.generateGet(tableName, pascalName));

    // 2. list - List all documents with optional pagination
    queries.push(this.generateList(tableName, pascalName));

    // 3. getBy[Field] - Get by indexed/unique fields
    const getByQueries = this.generateGetByFields(table, tableName, pascalName);
    queries.push(...getByQueries);

    // 4. search - Full-text search if text fields exist
    const textFields = table.columns.filter((col) =>
      ['text', 'varchar', 'character varying'].includes(
        col.dataType.toLowerCase()
      )
    );
    if (textFields.length > 0) {
      queries.push(this.generateSearch(tableName, pascalName, textFields));
    }

    // 5. count - Count documents
    queries.push(this.generateCount(tableName, pascalName));

    const content = `// Generated queries for ${table.tableName}
// Do not edit this file directly - it will be overwritten
//
// AUTHENTICATION: To require auth, add to any handler:
//   const identity = await ctx.auth.getUserIdentity();
//   if (!identity) throw new Error("Unauthenticated");
// See: https://docs.convex.dev/auth

import { query } from "./_generated/server";
import { v } from "convex/values";

${queries.join('\n\n')}
`;

    return { content, count: queries.length };
  }

  /**
   * Generate get query
   */
  private generateGet(tableName: string, pascalName: string): string {
    // Convex 1.31+ requires table name as first parameter
    const getCall = this.useNewApiStyle()
      ? `ctx.db.get("${tableName}", args.id)`
      : `ctx.db.get(args.id)`;

    return `/**
 * Get a single ${pascalName} by ID
 */
export const get = query({
  args: {
    id: v.id("${tableName}"),
  },
  handler: async (ctx, args) => {
    return await ${getCall};
  },
});`;
  }

  /**
   * Generate list query with pagination
   */
  private generateList(tableName: string, pascalName: string): string {
    return `/**
 * List all ${pascalName} documents with optional pagination
 */
export const list = query({
  args: {
    limit: v.optional(v.number()),
    cursor: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const limit = args.limit ?? 50;

    const results = await ctx.db
      .query("${tableName}")
      .order("desc")
      .take(limit + 1);

    const hasMore = results.length > limit;
    const items = hasMore ? results.slice(0, -1) : results;
    const nextCursor = hasMore && items.length > 0 ? items[items.length - 1]._id : undefined;

    return {
      items,
      nextCursor,
      hasMore,
    };
  },
});`;
  }

  /**
   * Generate getBy queries for indexed fields
   */
  private generateGetByFields(
    table: TableInfo,
    tableName: string,
    pascalName: string
  ): string[] {
    const queries: string[] = [];

    // Generate getBy for foreign keys
    for (const fk of table.foreignKeys) {
      const fieldName = this.toCamelCase(fk.columnName);
      const methodName = `getBy${this.toPascalCase(fk.columnName)}`;
      const indexName = `by_${fieldName}`;
      const refTable = fk.referencedTable;

      queries.push(`/**
 * Get ${pascalName} documents by ${fieldName}
 */
export const ${methodName} = query({
  args: {
    ${fieldName}: v.id("${refTable}"),
  },
  handler: async (ctx, args) => {
    return await ctx.db
      .query("${tableName}")
      .withIndex("${indexName}", (q) => q.eq("${fieldName}", args.${fieldName}))
      .collect();
  },
});`);
    }

    // Generate getBy for unique indexed fields
    const uniqueFields = table.indexes.filter(
      (idx) =>
        idx.isUnique &&
        !table.primaryKeys.includes(idx.columnName) &&
        !idx.indexName.endsWith('_pkey')
    );

    const addedMethods = new Set<string>();
    for (const idx of uniqueFields) {
      const fieldName = this.toCamelCase(idx.columnName);
      const methodName = `getBy${this.toPascalCase(idx.columnName)}`;

      if (addedMethods.has(methodName)) continue;
      addedMethods.add(methodName);

      const indexName = `by_${fieldName}`;
      const column = table.columns.find((c) => c.columnName === idx.columnName);
      const convexType = column ? this.getConvexArgType(column) : 'v.string()';

      queries.push(`/**
 * Get a ${pascalName} by unique ${fieldName}
 */
export const ${methodName} = query({
  args: {
    ${fieldName}: ${convexType},
  },
  handler: async (ctx, args) => {
    return await ctx.db
      .query("${tableName}")
      .withIndex("${indexName}", (q) => q.eq("${fieldName}", args.${fieldName}))
      .unique();
  },
});`);
    }

    return queries;
  }

  /**
   * Generate search query
   */
  private generateSearch(
    tableName: string,
    pascalName: string,
    textFields: ColumnInfo[]
  ): string {
    const searchFields = textFields.slice(0, 3); // Limit to 3 fields
    const fieldNames = searchFields.map((f) => this.toCamelCase(f.columnName));

    const fieldChecks = fieldNames
      .map(
        (f) => `const ${f}Match = doc.${f}?.toLowerCase().includes(searchTerm);`
      )
      .join('\n        ');

    const returnCondition = fieldNames.map((f) => `${f}Match`).join(' || ');

    return `/**
 * Search ${pascalName} documents by text fields
 * Searches in: ${fieldNames.join(', ')}
 */
export const search = query({
  args: {
    searchQuery: v.string(),
    limit: v.optional(v.number()),
  },
  handler: async (ctx, args) => {
    const limit = args.limit ?? 20;
    const searchTerm = args.searchQuery.toLowerCase();

    // Note: For production, consider using Convex search indexes
    const all = await ctx.db.query("${tableName}").collect();

    return all
      .filter((doc) => {
        ${fieldChecks}
        return ${returnCondition};
      })
      .slice(0, limit);
  },
});`;
  }

  /**
   * Generate count query
   */
  private generateCount(tableName: string, pascalName: string): string {
    return `/**
 * Count all ${pascalName} documents
 */
export const count = query({
  args: {},
  handler: async (ctx) => {
    const results = await ctx.db.query("${tableName}").collect();
    return results.length;
  },
});`;
  }

  /**
   * Get Convex arg type for a column
   */
  private getConvexArgType(column: ColumnInfo): string {
    const cleanType = column.dataType.split('(')[0].toLowerCase();

    switch (cleanType) {
      case 'integer':
      case 'int':
      case 'smallint':
      case 'bigint':
      case 'decimal':
      case 'numeric':
      case 'real':
      case 'float':
      case 'double precision':
        return 'v.number()';
      case 'boolean':
      case 'bool':
        return 'v.boolean()';
      default:
        return 'v.string()';
    }
  }

  /**
   * Convert snake_case to camelCase
   */
  private toCamelCase(str: string): string {
    return str.replace(/_([a-z])/g, (_, letter) => letter.toUpperCase());
  }

  /**
   * Convert to PascalCase
   */
  private toPascalCase(str: string): string {
    const camel = this.toCamelCase(str);
    return camel.charAt(0).toUpperCase() + camel.slice(1);
  }
}
