/**
 * Convex Query Generator
 *
 * Generates query functions for Convex:
 * - get: Get single document by ID
 * - list: List all documents with pagination
 * - getBy[Field]: Get by indexed fields
 * - search: Full-text search (if text fields exist)
 * - count: Count all documents
 *
 * Supports Convex API versions:
 * - 1.30: Uses old API style (db.get(docId))
 * - 1.31+: Uses new API style (db.get("tableName", docId))
 */

import type {
  TableInfo,
  ColumnInfo,
} from '../../introspector/schema-introspector.js';
import type {
  QueryGeneratorResult,
  ConvexApiVersion,
} from '../../convex/types.js';

/**
 * Options for the query generator
 */
export interface QueryGeneratorOptions {
  /**
   * Convex API version to target
   * - '1.30': Old API style (db.get(docId))
   * - '1.31': New API style (db.get("tableName", docId))
   * Default: '1.30' for backwards compatibility
   */
  convexApiVersion?: ConvexApiVersion;
}

/**
 * Generates Convex query functions
 */
export class QueryGenerator {
  private options: QueryGeneratorOptions;

  constructor(options: QueryGeneratorOptions = {}) {
    this.options = {
      convexApiVersion: '1.30',
      ...options,
    };
  }

  /**
   * Check if using Convex 1.31+ API style
   */
  private useNewApiStyle(): boolean {
    return this.options.convexApiVersion === '1.31';
  }
  /**
   * Generate all queries for a table
   */
  generate(table: TableInfo): QueryGeneratorResult {
    const tableName = table.tableName;
    const pascalName = this.toPascalCase(tableName);

    const queries: string[] = [];

    // 1. get - Get single document by ID
    queries.push(this.generateGet(tableName, pascalName));

    // 2. list - List all documents with optional pagination
    queries.push(this.generateList(tableName, pascalName));

    // 3. getBy[Field] - Get by indexed/unique fields
    const getByQueries = this.generateGetByFields(table, tableName, pascalName);
    queries.push(...getByQueries);

    // 4. search - Full-text search if text fields exist
    const textFields = table.columns.filter((col) =>
      ['text', 'varchar', 'character varying'].includes(
        col.dataType.toLowerCase()
      )
    );
    if (textFields.length > 0) {
      queries.push(this.generateSearch(tableName, pascalName, textFields));
    }

    // 5. count - Count documents
    queries.push(this.generateCount(tableName, pascalName));

    const content = `// Generated queries for ${table.tableName}
// Do not edit this file directly - it will be overwritten
//
// AUTHENTICATION: To require auth, add to any handler:
//   const identity = await ctx.auth.getUserIdentity();
//   if (!identity) throw new Error("Unauthenticated");
// See: https://docs.convex.dev/auth

import { query } from "./_generated/server";
import { v } from "convex/values";

${queries.join('\n\n')}
`;

    return { content, count: queries.length };
  }

  /**
   * Generate get query
   */
  private generateGet(tableName: string, pascalName: string): string {
    // Convex 1.31+ requires table name as first parameter
    const getCall = this.useNewApiStyle()
      ? `ctx.db.get("${tableName}", args.id)`
      : `ctx.db.get(args.id)`;

    return `/**
 * Get a single ${pascalName} by ID
 *
 * @example
 * \`\`\`typescript
 * // React usage:
 * import { useQuery } from "convex/react";
 * import { api } from "./_generated/api";
 *
 * function ${pascalName}Detail({ id }: { id: Id<"${tableName}"> }) {
 *   const ${this.toCamelCase(tableName)} = useQuery(api.${tableName}.get, { id });
 *   return <div>{${this.toCamelCase(tableName)}?.name}</div>;
 * }
 * \`\`\`
 *
 * @param args.id - The document ID
 * @returns The ${pascalName} document or null if not found
 */
export const get = query({
  args: {
    id: v.id("${tableName}"),
  },
  handler: async (ctx, args): Promise<typeof ctx.db extends { get: (table: "${tableName}", id: Id<"${tableName}">) => Promise<infer T> } ? T : any> => {
    return await ${getCall};
  },
});`;
  }

  /**
   * Generate list query with pagination
   */
  private generateList(tableName: string, pascalName: string): string {
    return `/**
 * List all ${pascalName} documents with cursor-based pagination
 *
 * Uses Convex's official paginate() API for efficient cursor-based pagination.
 * See: https://docs.convex.dev/database/pagination
 *
 * @example
 * \`\`\`typescript
 * // React usage with usePaginatedQuery:
 * import { usePaginatedQuery } from "convex/react";
 * import { api } from "./_generated/api";
 *
 * function ${pascalName}List() {
 *   const { results, status, loadMore } = usePaginatedQuery(
 *     api.${tableName}.list,
 *     {},
 *     { initialNumItems: 20 }
 *   );
 *
 *   return (
 *     <div>
 *       {results.map(item => <div key={item._id}>{item.name}</div>)}
 *       <button onClick={() => loadMore(20)} disabled={status !== "CanLoadMore"}>
 *         Load More
 *       </button>
 *     </div>
 *   );
 * }
 * \`\`\`
 *
 * @param args.paginationOpts - Pagination options (numItems, cursor, endCursor)
 * @returns Paginated results with continuation cursor
 */
export const list = query({
  args: {
    paginationOpts: v.optional(v.object({
      numItems: v.number(),
      cursor: v.union(v.string(), v.null()),
      endCursor: v.optional(v.union(v.string(), v.null())),
    })),
  },
  handler: async (ctx, args) => {
    return await ctx.db
      .query("${tableName}")
      .order("desc")
      .paginate(args.paginationOpts ?? { numItems: 50, cursor: null });
  },
});`;
  }

  /**
   * Generate getBy queries for indexed fields
   */
  private generateGetByFields(
    table: TableInfo,
    tableName: string,
    pascalName: string
  ): string[] {
    const queries: string[] = [];

    // Generate getBy for foreign keys
    for (const fk of table.foreignKeys) {
      const fieldName = this.toCamelCase(fk.columnName);
      const methodName = `getBy${this.toPascalCase(fk.columnName)}`;
      const indexName = `by_${fieldName}`;
      const refTable = fk.referencedTable;

      queries.push(`/**
 * Get ${pascalName} documents by ${fieldName}
 *
 * Uses index for efficient lookup by foreign key reference.
 *
 * @example
 * \`\`\`typescript
 * // React usage:
 * import { useQuery } from "convex/react";
 * import { api } from "./_generated/api";
 *
 * function ${pascalName}sByRef({ ${fieldName} }: { ${fieldName}: Id<"${refTable}"> }) {
 *   const items = useQuery(api.${tableName}.${methodName}, { ${fieldName} });
 *   return <div>{items?.length} ${pascalName}(s) found</div>;
 * }
 * \`\`\`
 *
 * @param args.${fieldName} - The ${refTable} reference ID
 * @returns Array of ${pascalName} documents matching the ${fieldName}
 */
export const ${methodName} = query({
  args: {
    ${fieldName}: v.id("${refTable}"),
  },
  handler: async (ctx, args) => {
    return await ctx.db
      .query("${tableName}")
      .withIndex("${indexName}", (q) => q.eq("${fieldName}", args.${fieldName}))
      .collect();
  },
});`);
    }

    // Generate getBy for unique indexed fields
    const uniqueFields = table.indexes.filter(
      (idx) =>
        idx.isUnique &&
        !table.primaryKeys.includes(idx.columnName) &&
        !idx.indexName.endsWith('_pkey')
    );

    const addedMethods = new Set<string>();
    for (const idx of uniqueFields) {
      const fieldName = this.toCamelCase(idx.columnName);
      const methodName = `getBy${this.toPascalCase(idx.columnName)}`;

      if (addedMethods.has(methodName)) continue;
      addedMethods.add(methodName);

      const indexName = `by_${fieldName}`;
      const column = table.columns.find((c) => c.columnName === idx.columnName);
      const convexType = column ? this.getConvexArgType(column) : 'v.string()';

      queries.push(`/**
 * Get a ${pascalName} by unique ${fieldName}
 *
 * Uses unique index for efficient O(1) lookup.
 *
 * @example
 * \`\`\`typescript
 * // React usage:
 * import { useQuery } from "convex/react";
 * import { api } from "./_generated/api";
 *
 * function ${pascalName}ByField({ ${fieldName} }: { ${fieldName}: string }) {
 *   const item = useQuery(api.${tableName}.${methodName}, { ${fieldName} });
 *   return <div>{item?.name || "Not found"}</div>;
 * }
 * \`\`\`
 *
 * @param args.${fieldName} - The unique ${fieldName} value
 * @returns The ${pascalName} document or null if not found
 */
export const ${methodName} = query({
  args: {
    ${fieldName}: ${convexType},
  },
  handler: async (ctx, args) => {
    return await ctx.db
      .query("${tableName}")
      .withIndex("${indexName}", (q) => q.eq("${fieldName}", args.${fieldName}))
      .unique();
  },
});`);
    }

    return queries;
  }

  /**
   * Generate search query
   */
  private generateSearch(
    tableName: string,
    pascalName: string,
    textFields: ColumnInfo[]
  ): string {
    const searchFields = textFields.slice(0, 3); // Limit to 3 fields
    const fieldNames = searchFields.map((f) => this.toCamelCase(f.columnName));
    const primarySearchField = fieldNames[0];

    return `/**
 * Search ${pascalName} documents using full-text search
 *
 * Uses Convex search indexes for efficient full-text search.
 * Primary search field: ${primarySearchField}
 * See: https://docs.convex.dev/text-search
 *
 * NOTE: For this search to work, you must enable search indexes in schema.ts.
 * Add the following to your SchemaGenerator options:
 * \`\`\`typescript
 * new SchemaGenerator({ generateSearchIndexes: true })
 * \`\`\`
 *
 * @example
 * \`\`\`typescript
 * // React usage:
 * import { useQuery } from "convex/react";
 * import { api } from "./_generated/api";
 *
 * function ${pascalName}Search() {
 *   const [searchTerm, setSearchTerm] = useState("");
 *   const results = useQuery(api.${tableName}.search, { searchQuery: searchTerm });
 *
 *   return (
 *     <div>
 *       <input value={searchTerm} onChange={(e) => setSearchTerm(e.target.value)} />
 *       {results?.map(item => <div key={item._id}>{item.${primarySearchField}}</div>)}
 *     </div>
 *   );
 * }
 * \`\`\`
 *
 * @param args.searchQuery - The search query string
 * @param args.limit - Maximum number of results (default: 20)
 * @returns Array of matching ${pascalName} documents
 */
export const search = query({
  args: {
    searchQuery: v.string(),
    limit: v.optional(v.number()),
  },
  handler: async (ctx, args) => {
    const limit = args.limit ?? 20;

    // Use Convex search index for efficient full-text search
    // This requires search index to be defined in schema.ts
    const results = await ctx.db
      .query("${tableName}")
      .withSearchIndex("search_${primarySearchField}", (q) => q.search("${primarySearchField}", args.searchQuery))
      .take(limit);

    return results;
  },
});`;
  }

  /**
   * Generate count query
   */
  private generateCount(tableName: string, pascalName: string): string {
    return `/**
 * Count all ${pascalName} documents
 *
 * @example
 * \`\`\`typescript
 * // React usage:
 * import { useQuery } from "convex/react";
 * import { api } from "./_generated/api";
 *
 * function ${pascalName}Stats() {
 *   const count = useQuery(api.${tableName}.count);
 *   return <div>Total ${pascalName}: {count}</div>;
 * }
 * \`\`\`
 *
 * @returns The total number of ${pascalName} documents
 */
export const count = query({
  args: {},
  handler: async (ctx): Promise<number> => {
    const results = await ctx.db.query("${tableName}").collect();
    return results.length;
  },
});`;
  }

  /**
   * Get Convex arg type for a column
   */
  private getConvexArgType(column: ColumnInfo): string {
    const cleanType = column.dataType.split('(')[0].toLowerCase();

    switch (cleanType) {
      case 'integer':
      case 'int':
      case 'smallint':
      case 'bigint':
      case 'decimal':
      case 'numeric':
      case 'real':
      case 'float':
      case 'double precision':
        return 'v.number()';
      case 'boolean':
      case 'bool':
        return 'v.boolean()';
      default:
        return 'v.string()';
    }
  }

  /**
   * Convert snake_case to camelCase
   */
  private toCamelCase(str: string): string {
    return str.replace(/_([a-z])/g, (_, letter) => letter.toUpperCase());
  }

  /**
   * Convert to PascalCase
   */
  private toPascalCase(str: string): string {
    const camel = this.toCamelCase(str);
    return camel.charAt(0).toUpperCase() + camel.slice(1);
  }
}
