/**
 * React Hooks Generator
 *
 * Generates type-safe React hooks for Convex queries and mutations.
 * Creates ready-to-use hooks with loading states and error handling.
 */

import type {
  ConvexTableDefinition,
  ConvexFieldMapping,
} from '../../convex/types.js';
import { toPascalCase, toCamelCase } from '../../shared/types.js';

/**
 * Options for React hooks generation
 */
export interface ReactHooksGeneratorOptions {
  /** Output directory for generated hooks */
  outputDir: string;
  /** Generate individual hook files per table */
  separateFiles: boolean;
  /** Include JSDoc comments */
  includeComments: boolean;
  /** Generate React Query integration */
  useReactQuery: boolean;
  /** Generate optimistic update helpers */
  generateOptimisticUpdates: boolean;
  /** Generate loading skeleton components */
  generateSkeletons: boolean;
  /** Import path prefix for Convex functions */
  convexFunctionsPath: string;
}

const DEFAULT_OPTIONS: ReactHooksGeneratorOptions = {
  outputDir: './src/hooks',
  separateFiles: true,
  includeComments: true,
  useReactQuery: false,
  generateOptimisticUpdates: true,
  generateSkeletons: false,
  convexFunctionsPath: '../convex',
};

/**
 * Generated hooks result
 */
export interface ReactHooksResult {
  /** Main hooks file content */
  content: string;
  /** Per-table hook files (if separateFiles is true) */
  files: Map<string, string>;
  /** Number of hooks generated */
  hookCount: number;
}

/**
 * React Hooks Generator
 */
export class ReactHooksGenerator {
  private options: ReactHooksGeneratorOptions;

  constructor(options: Partial<ReactHooksGeneratorOptions> = {}) {
    this.options = { ...DEFAULT_OPTIONS, ...options };
  }

  /**
   * Generate React hooks for all tables
   */
  generate(tables: ConvexTableDefinition[]): ReactHooksResult {
    const files = new Map<string, string>();
    let totalHooks = 0;

    // Generate hooks for each table
    for (const table of tables) {
      const { content, hookCount } = this.generateTableHooks(table);
      files.set(`use${toPascalCase(table.tableName)}.ts`, content);
      totalHooks += hookCount;
    }

    // Generate index file
    const indexContent = this.generateIndexFile(tables);
    files.set('index.ts', indexContent);

    // Generate combined hooks file
    const combinedContent = this.generateCombinedFile(tables);

    return {
      content: combinedContent,
      files,
      hookCount: totalHooks,
    };
  }

  /**
   * Generate hooks for a single table
   */
  private generateTableHooks(table: ConvexTableDefinition): {
    content: string;
    hookCount: number;
  } {
    const tableName = table.tableName;
    const pascalName = toPascalCase(tableName);
    // camelName used in hook function names
    const camelName = toCamelCase(tableName);

    const lines: string[] = [];
    let hookCount = 0;

    // File header - uses pascalName for usage examples
    lines.push(this.generateFileHeader(tableName, pascalName));
    lines.push('');

    // Imports - uses pascalName for type imports
    lines.push(this.generateImports(tableName, pascalName, camelName));
    lines.push('');

    // Types
    lines.push(this.generateTypes(table));
    lines.push('');

    // useList hook
    lines.push(this.generateUseListHook(table));
    hookCount++;
    lines.push('');

    // useGet hook
    lines.push(this.generateUseGetHook(table));
    hookCount++;
    lines.push('');

    // useCreate hook
    lines.push(this.generateUseCreateHook(table));
    hookCount++;
    lines.push('');

    // useUpdate hook
    lines.push(this.generateUseUpdateHook(table));
    hookCount++;
    lines.push('');

    // useRemove hook
    lines.push(this.generateUseRemoveHook(table));
    hookCount++;
    lines.push('');

    // useSearch hook (if text fields exist)
    const textFields = table.fields.filter(
      (f) =>
        f.validator.includes('v.string()') &&
        !f.isId &&
        !f.fieldName.includes('Id')
    );
    if (textFields.length > 0) {
      lines.push(this.generateUseSearchHook(table, textFields));
      hookCount++;
      lines.push('');
    }

    // Optimistic update helpers
    if (this.options.generateOptimisticUpdates) {
      lines.push(this.generateOptimisticHelpers(table));
    }

    return {
      content: lines.join('\n'),
      hookCount,
    };
  }

  /**
   * Generate file header
   */
  private generateFileHeader(tableName: string, pascalName: string): string {
    if (!this.options.includeComments) return '';

    return `/**
 * React Hooks for ${tableName}
 *
 * Auto-generated by SunSetter AQM+
 * These hooks provide type-safe access to Convex queries and mutations.
 *
 * Usage:
 *   const { data, isLoading } = use${pascalName}List();
 *   const createMutation = useCreate${pascalName}();
 */`;
  }

  /**
   * Generate imports
   * @param _tableName - Table name (for future use in custom imports)
   * @param _pascalName - PascalCase name (for future type imports)
   * @param _camelName - camelCase name (for future named imports)
   */
  private generateImports(
    _tableName: string,
    _pascalName: string,
    _camelName: string
  ): string {
    const path = this.options.convexFunctionsPath;

    return `import { useQuery, useMutation } from 'convex/react';
import { api } from '${path}/_generated/api';
import type { Id } from '${path}/_generated/dataModel';
import type { FunctionReference } from 'convex/server';
import { useCallback, useMemo } from 'react';`;
  }

  /**
   * Generate TypeScript types
   */
  private generateTypes(table: ConvexTableDefinition): string {
    const pascalName = toPascalCase(table.tableName);
    const fields = table.fields;

    // Document type
    const docFields = fields
      .map((f) => {
        const optional = f.isOptional ? '?' : '';
        const type = this.validatorToTsType(f.validator, f.referencedTable);
        return `  ${f.fieldName}${optional}: ${type};`;
      })
      .join('\n');

    // Create input type (without _id and _creationTime)
    const createFields = fields
      .filter((f) => !['_id', '_creationTime'].includes(f.originalColumnName))
      .map((f) => {
        const optional = f.isOptional ? '?' : '';
        const type = this.validatorToTsType(f.validator, f.referencedTable);
        return `  ${f.fieldName}${optional}: ${type};`;
      })
      .join('\n');

    // Update input type (all optional)
    const updateFields = fields
      .filter((f) => !['_id', '_creationTime'].includes(f.originalColumnName))
      .map((f) => {
        const type = this.validatorToTsType(f.validator, f.referencedTable);
        return `  ${f.fieldName}?: ${type};`;
      })
      .join('\n');

    return `/**
 * ${pascalName} document type
 */
export interface ${pascalName} {
  _id: Id<"${table.tableName}">;
  _creationTime: number;
${docFields}
}

/**
 * Input for creating a new ${pascalName}
 */
export interface Create${pascalName}Input {
${createFields}
}

/**
 * Input for updating a ${pascalName}
 */
export interface Update${pascalName}Input {
${updateFields}
}

/**
 * Filter options for listing ${pascalName}s
 */
export interface ${pascalName}FilterOptions {
  limit?: number;
  cursor?: string;
  sortBy?: keyof ${pascalName};
  sortOrder?: 'asc' | 'desc';
}`;
  }

  /**
   * Generate useList hook
   */
  private generateUseListHook(table: ConvexTableDefinition): string {
    const pascalName = toPascalCase(table.tableName);
    const camelName = toCamelCase(table.tableName);

    const comment = this.options.includeComments
      ? `/**
 * Hook to list ${table.tableName} documents
 *
 * @param options - Filter and pagination options
 * @returns Query result with data, loading state, and error
 *
 * @example
 * const { data, isLoading, error } = use${pascalName}List({ limit: 10 });
 */`
      : '';

    return `${comment}
export function use${pascalName}List(options: ${pascalName}FilterOptions = {}) {
  const { limit = 50, cursor, sortBy, sortOrder } = options;

  const result = useQuery(api.${camelName}.list, {
    limit,
    cursor,
  });

  return useMemo(() => ({
    data: result ?? [],
    isLoading: result === undefined,
    isEmpty: result !== undefined && result.length === 0,
    error: null, // Convex handles errors differently
  }), [result]);
}`;
  }

  /**
   * Generate useGet hook
   */
  private generateUseGetHook(table: ConvexTableDefinition): string {
    const pascalName = toPascalCase(table.tableName);
    const camelName = toCamelCase(table.tableName);

    const comment = this.options.includeComments
      ? `/**
 * Hook to get a single ${table.tableName} by ID
 *
 * @param id - Document ID
 * @returns Query result with data, loading state, and not found status
 *
 * @example
 * const { data, isLoading, notFound } = use${pascalName}(id);
 */`
      : '';

    return `${comment}
export function use${pascalName}(id: Id<"${table.tableName}"> | undefined) {
  const result = useQuery(
    api.${camelName}.getById,
    id ? { id } : 'skip'
  );

  return useMemo(() => ({
    data: result ?? null,
    isLoading: id !== undefined && result === undefined,
    notFound: result === null,
    error: null,
  }), [result, id]);
}`;
  }

  /**
   * Generate useCreate hook
   */
  private generateUseCreateHook(table: ConvexTableDefinition): string {
    const pascalName = toPascalCase(table.tableName);
    const camelName = toCamelCase(table.tableName);

    const comment = this.options.includeComments
      ? `/**
 * Hook to create a new ${table.tableName}
 *
 * @returns Mutation function and state
 *
 * @example
 * const { mutate, isLoading } = useCreate${pascalName}();
 * await mutate({ name: 'New Item' });
 */`
      : '';

    return `${comment}
export function useCreate${pascalName}() {
  const mutation = useMutation(api.${camelName}.create);

  const mutate = useCallback(
    async (input: Create${pascalName}Input) => {
      return await mutation(input);
    },
    [mutation]
  );

  return {
    mutate,
    mutateAsync: mutate,
  };
}`;
  }

  /**
   * Generate useUpdate hook
   */
  private generateUseUpdateHook(table: ConvexTableDefinition): string {
    const pascalName = toPascalCase(table.tableName);
    const camelName = toCamelCase(table.tableName);

    const comment = this.options.includeComments
      ? `/**
 * Hook to update an existing ${table.tableName}
 *
 * @returns Mutation function and state
 *
 * @example
 * const { mutate } = useUpdate${pascalName}();
 * await mutate(id, { name: 'Updated Name' });
 */`
      : '';

    return `${comment}
export function useUpdate${pascalName}() {
  const mutation = useMutation(api.${camelName}.update);

  const mutate = useCallback(
    async (id: Id<"${table.tableName}">, input: Update${pascalName}Input) => {
      return await mutation({ id, ...input });
    },
    [mutation]
  );

  return {
    mutate,
    mutateAsync: mutate,
  };
}`;
  }

  /**
   * Generate useRemove hook
   */
  private generateUseRemoveHook(table: ConvexTableDefinition): string {
    const pascalName = toPascalCase(table.tableName);
    const camelName = toCamelCase(table.tableName);

    const comment = this.options.includeComments
      ? `/**
 * Hook to remove a ${table.tableName}
 *
 * @returns Mutation function and state
 *
 * @example
 * const { mutate } = useRemove${pascalName}();
 * await mutate(id);
 */`
      : '';

    return `${comment}
export function useRemove${pascalName}() {
  const mutation = useMutation(api.${camelName}.remove);

  const mutate = useCallback(
    async (id: Id<"${table.tableName}">) => {
      return await mutation({ id });
    },
    [mutation]
  );

  return {
    mutate,
    mutateAsync: mutate,
  };
}`;
  }

  /**
   * Generate useSearch hook
   */
  private generateUseSearchHook(
    table: ConvexTableDefinition,
    textFields: ConvexFieldMapping[]
  ): string {
    const pascalName = toPascalCase(table.tableName);
    const camelName = toCamelCase(table.tableName);
    const searchableFields = textFields.map((f) => f.fieldName).join(', ');

    const comment = this.options.includeComments
      ? `/**
 * Hook to search ${table.tableName} by text
 *
 * Searchable fields: ${searchableFields}
 *
 * @param query - Search query string
 * @param options - Search options
 * @returns Search results
 *
 * @example
 * const { data, isLoading } = useSearch${pascalName}('query');
 */`
      : '';

    return `${comment}
export function useSearch${pascalName}(
  query: string,
  options: { limit?: number } = {}
) {
  const { limit = 20 } = options;

  const result = useQuery(
    api.${camelName}.search,
    query.trim() ? { query, limit } : 'skip'
  );

  return useMemo(() => ({
    data: result ?? [],
    isLoading: query.trim() !== '' && result === undefined,
    isEmpty: result !== undefined && result.length === 0,
    query,
  }), [result, query]);
}`;
  }

  /**
   * Generate optimistic update helpers
   */
  private generateOptimisticHelpers(table: ConvexTableDefinition): string {
    const pascalName = toPascalCase(table.tableName);
    const camelName = toCamelCase(table.tableName);

    if (!this.options.includeComments) {
      return `// Optimistic update helpers for ${pascalName}
export const ${camelName}OptimisticHelpers = {
  addToList: <T extends { _id: string }>(list: T[], item: T) => [...list, item],
  removeFromList: <T extends { _id: string }>(list: T[], id: string) =>
    list.filter((item) => item._id !== id),
  updateInList: <T extends { _id: string }>(list: T[], id: string, updates: Partial<T>) =>
    list.map((item) => (item._id === id ? { ...item, ...updates } : item)),
};`;
    }

    return `/**
 * Optimistic update helpers for ${pascalName}
 *
 * Use these with React Query or local state to provide instant UI updates
 * while waiting for the server to confirm changes.
 */
export const ${camelName}OptimisticHelpers = {
  /**
   * Optimistically add an item to a list
   */
  addToList: <T extends { _id: string }>(list: T[], item: T): T[] => [...list, item],

  /**
   * Optimistically remove an item from a list
   */
  removeFromList: <T extends { _id: string }>(list: T[], id: string): T[] =>
    list.filter((item) => item._id !== id),

  /**
   * Optimistically update an item in a list
   */
  updateInList: <T extends { _id: string }>(
    list: T[],
    id: string,
    updates: Partial<T>
  ): T[] => list.map((item) => (item._id === id ? { ...item, ...updates } : item)),
};`;
  }

  /**
   * Generate index file that exports all hooks
   */
  private generateIndexFile(tables: ConvexTableDefinition[]): string {
    const exports = tables
      .map((t) => {
        const pascalName = toPascalCase(t.tableName);
        return `export * from './use${pascalName}';`;
      })
      .join('\n');

    return `/**
 * React Hooks for Convex
 *
 * Auto-generated by SunSetter AQM+
 */

${exports}
`;
  }

  /**
   * Generate combined hooks file
   */
  private generateCombinedFile(tables: ConvexTableDefinition[]): string {
    const lines: string[] = [];

    lines.push(`/**
 * React Hooks for Convex
 *
 * Auto-generated by SunSetter AQM+
 * This file contains all hooks for all tables.
 */

import { useQuery, useMutation } from 'convex/react';
import { api } from '${this.options.convexFunctionsPath}/_generated/api';
import type { Id } from '${this.options.convexFunctionsPath}/_generated/dataModel';
import { useCallback, useMemo } from 'react';
`);

    for (const table of tables) {
      const { content } = this.generateTableHooks(table);
      // Strip imports from individual table content
      const contentWithoutImports = content
        .split('\n')
        .filter((line) => !line.startsWith('import '))
        .join('\n');
      lines.push(contentWithoutImports);
      lines.push('');
    }

    return lines.join('\n');
  }

  /**
   * Convert Convex validator to TypeScript type
   */
  private validatorToTsType(
    validator: string,
    referencedTable?: string
  ): string {
    if (referencedTable) {
      return `Id<"${referencedTable}">`;
    }

    if (validator.includes('v.string()')) return 'string';
    if (validator.includes('v.number()')) return 'number';
    if (validator.includes('v.float64()')) return 'number';
    if (validator.includes('v.int64()')) return 'number';
    if (validator.includes('v.boolean()')) return 'boolean';
    if (validator.includes('v.null()')) return 'null';
    if (validator.includes('v.any()')) return 'unknown';
    if (validator.includes('v.bytes()')) return 'ArrayBuffer';
    if (validator.includes('v.array(')) return 'unknown[]';
    if (validator.includes('v.object(')) return 'Record<string, unknown>';
    if (validator.includes('v.id(')) {
      const match = validator.match(/v\.id\("([^"]+)"\)/);
      if (match) return `Id<"${match[1]}">`;
    }

    return 'unknown';
  }
}

/**
 * Generate React hooks for tables
 */
export function generateReactHooks(
  tables: ConvexTableDefinition[],
  options: Partial<ReactHooksGeneratorOptions> = {}
): ReactHooksResult {
  const generator = new ReactHooksGenerator(options);
  return generator.generate(tables);
}
