/**
 * Convex Schema Generator
 *
 * Generates the main schema.ts file with all table definitions,
 * validators, indexes, search indexes, and vector indexes.
 */

import type {
  TableInfo,
  ColumnInfo,
} from '../../introspector/schema-introspector.js';
import {
  toCamelCase,
  escapeFieldName,
  isReservedWord,
} from '../../shared/types.js';

/**
 * Configuration for search index generation
 */
export interface SearchIndexConfig {
  /** Index name */
  indexName: string;
  /** Field to search on */
  searchField: string;
  /** Filter fields for the search index */
  filterFields: string[];
}

/**
 * Configuration for vector index generation
 */
export interface VectorIndexConfig {
  /** Index name */
  indexName: string;
  /** Field containing the vector */
  vectorField: string;
  /** Number of dimensions */
  dimensions: number;
  /** Filter fields for the vector index */
  filterFields: string[];
}

/**
 * Options for schema generation
 */
export interface SchemaGeneratorOptions {
  /** Generate search indexes for text fields */
  generateSearchIndexes?: boolean;
  /** Generate vector indexes for embedding fields */
  generateVectorIndexes?: boolean;
  /** Default vector dimensions (default: 1536 for OpenAI) */
  defaultVectorDimensions?: number;
  /** Use staged deployment for large table indexes */
  useStagedIndexes?: boolean;
  /** Custom search index configurations by table */
  searchIndexConfigs?: Record<string, SearchIndexConfig[]>;
  /** Custom vector index configurations by table */
  vectorIndexConfigs?: Record<string, VectorIndexConfig[]>;
}

/**
 * Generates Convex schema.ts content from table definitions
 */
export class SchemaGenerator {
  private options: SchemaGeneratorOptions;

  constructor(options: SchemaGeneratorOptions = {}) {
    this.options = {
      generateSearchIndexes: false,
      generateVectorIndexes: false,
      defaultVectorDimensions: 1536,
      useStagedIndexes: false,
      ...options,
    };
  }

  /**
   * Generate complete schema.ts content
   */
  generate(tables: TableInfo[]): string {
    const tableDefinitions = tables
      .map((table) => this.generateTableDefinition(table))
      .join('\n\n');

    return `// Generated Convex schema
// Do not edit this file directly - it will be overwritten

import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
${tableDefinitions}
});
`;
  }

  /**
   * Generate a single table definition
   */
  private generateTableDefinition(table: TableInfo): string {
    const tableName = table.tableName;
    const fields = table.columns
      .filter((col) => !this.shouldSkipColumn(col))
      .map((col) => this.generateFieldDefinition(col))
      .join(',\n');

    // Generate all index types
    const indexes = this.generateIndexes(table);
    const searchIndexes = this.generateSearchIndexes(table);
    const vectorIndexes = this.generateVectorIndexes(table);

    return `  ${tableName}: defineTable({
${fields}
  })${indexes}${searchIndexes}${vectorIndexes}`;
  }

  /**
   * Check if a column should be skipped
   */
  private shouldSkipColumn(column: ColumnInfo): boolean {
    // Skip auto-increment primary keys (Convex provides _id)
    if (column.isPrimaryKey && column.isIdentity) {
      return true;
    }
    // Skip columns named 'id' that are primary keys
    if (column.columnName.toLowerCase() === 'id' && column.isPrimaryKey) {
      return true;
    }
    return false;
  }

  /**
   * Generate a single field definition
   */
  private generateFieldDefinition(column: ColumnInfo): string {
    // Convert to camelCase and escape reserved words
    const rawFieldName = toCamelCase(column.columnName);
    const fieldName = escapeFieldName(rawFieldName);
    const convexType = this.getConvexValidator(column);

    // Add warning comment if field name was escaped
    let comment = column.description
      ? `    /** ${column.description} */\n`
      : '';
    if (fieldName !== rawFieldName) {
      comment = `    /** Original field name was a reserved word: ${rawFieldName} */\n`;
    }
    return `${comment}    ${fieldName}: ${convexType}`;
  }

  /**
   * Get the Convex validator for a column
   */
  private getConvexValidator(column: ColumnInfo): string {
    const baseType = this.mapToConvexType(column);

    // Handle foreign keys - table names match the schema (no transformation needed here
    // since both schema table definitions and FK references use the same raw names)
    if (column.isForeignKey && column.foreignKeyTable) {
      const fkType = `v.id("${column.foreignKeyTable}")`;
      return column.isNullable ? `v.optional(${fkType})` : fkType;
    }

    return column.isNullable ? `v.optional(${baseType})` : baseType;
  }

  /**
   * Map PostgreSQL type to Convex validator
   */
  private mapToConvexType(column: ColumnInfo): string {
    const cleanType = column.dataType.split('(')[0].toLowerCase();

    // Handle arrays
    if (column.dataType.includes('[]')) {
      const baseType = cleanType.replace('[]', '');
      const elementType = this.mapSimpleType(baseType);
      return `v.array(${elementType})`;
    }

    return this.mapSimpleType(cleanType);
  }

  /**
   * Map a simple PostgreSQL type to Convex validator
   */
  private mapSimpleType(pgType: string): string {
    const mapping: Record<string, string> = {
      // String types
      text: 'v.string()',
      varchar: 'v.string()',
      'character varying': 'v.string()',
      character: 'v.string()',
      char: 'v.string()',
      uuid: 'v.string()',
      citext: 'v.string()',

      // Number types
      integer: 'v.number()',
      int: 'v.number()',
      int4: 'v.number()',
      smallint: 'v.number()',
      bigint: 'v.number()',
      int8: 'v.number()',
      serial: 'v.number()',
      bigserial: 'v.number()',
      decimal: 'v.number()',
      numeric: 'v.number()',
      real: 'v.number()',
      float4: 'v.number()',
      'double precision': 'v.number()',
      float8: 'v.number()',
      money: 'v.number()',

      // Boolean
      boolean: 'v.boolean()',
      bool: 'v.boolean()',

      // Timestamps
      timestamp: 'v.number()',
      'timestamp without time zone': 'v.number()',
      'timestamp with time zone': 'v.number()',
      timestamptz: 'v.number()',
      date: 'v.number()',
      time: 'v.string()',
      interval: 'v.string()',

      // JSON
      json: 'v.any()',
      jsonb: 'v.any()',

      // Binary
      bytea: 'v.bytes()',
    };

    return mapping[pgType] || 'v.string()';
  }

  /**
   * Generate index definitions for a table
   */
  private generateIndexes(table: TableInfo): string {
    const indexes: string[] = [];

    // Add indexes for foreign keys
    for (const fk of table.foreignKeys) {
      const fieldName = toCamelCase(fk.columnName);
      indexes.push(`    .index("by_${fieldName}", ["${fieldName}"])`);
    }

    // Add indexes from unique constraints (excluding primary keys)
    const uniqueIndexes = table.indexes.filter(
      (idx) =>
        idx.isUnique &&
        !idx.indexName.endsWith('_pkey') &&
        !table.primaryKeys.includes(idx.columnName)
    );

    const addedIndexes = new Set<string>();
    for (const idx of uniqueIndexes) {
      const fieldName = toCamelCase(idx.columnName);
      const indexName = `by_${fieldName}`;

      if (!addedIndexes.has(indexName)) {
        indexes.push(`    .index("${indexName}", ["${fieldName}"])`);
        addedIndexes.add(indexName);
      }
    }

    if (indexes.length === 0) {
      return '';
    }

    return '\n' + indexes.join('\n');
  }

  /**
   * Generate search index definitions for a table
   * Search indexes enable full-text search on text fields
   */
  private generateSearchIndexes(table: TableInfo): string {
    if (!this.options.generateSearchIndexes) {
      return '';
    }

    const searchIndexes: string[] = [];

    // Check for custom configurations first
    const customConfigs = this.options.searchIndexConfigs?.[table.tableName];
    if (customConfigs && customConfigs.length > 0) {
      for (const config of customConfigs) {
        const filterFieldsStr =
          config.filterFields.length > 0
            ? `, filterFields: [${config.filterFields.map((f) => `"${f}"`).join(', ')}]`
            : '';
        searchIndexes.push(
          `    .searchIndex("${config.indexName}", { searchField: "${config.searchField}"${filterFieldsStr} })`
        );
      }
    } else {
      // Auto-detect text fields for search indexes
      const textFields = table.columns.filter((col) => {
        const cleanType = col.dataType.split('(')[0].toLowerCase();
        return ['text', 'varchar', 'character varying', 'citext'].includes(
          cleanType
        );
      });

      // Generate search index for each text field
      for (const col of textFields) {
        const fieldName = toCamelCase(col.columnName);
        const indexName = `search_${fieldName}`;

        // Find potential filter fields (non-text fields that might be useful for filtering)
        const filterFields = table.columns
          .filter((c) => {
            if (c.columnName === col.columnName) return false;
            if (this.shouldSkipColumn(c)) return false;
            const cleanType = c.dataType.split('(')[0].toLowerCase();
            // Include foreign keys, enums, and simple types as filter fields
            return (
              c.isForeignKey ||
              ['boolean', 'bool', 'integer', 'int', 'smallint'].includes(
                cleanType
              )
            );
          })
          .slice(0, 3) // Limit to 3 filter fields
          .map((c) => toCamelCase(c.columnName));

        const filterFieldsStr =
          filterFields.length > 0
            ? `, filterFields: [${filterFields.map((f) => `"${f}"`).join(', ')}]`
            : '';

        searchIndexes.push(
          `    .searchIndex("${indexName}", { searchField: "${fieldName}"${filterFieldsStr} })`
        );
      }
    }

    if (searchIndexes.length === 0) {
      return '';
    }

    return '\n' + searchIndexes.join('\n');
  }

  /**
   * Generate vector index definitions for a table
   * Vector indexes enable similarity search on embedding fields
   */
  private generateVectorIndexes(table: TableInfo): string {
    if (!this.options.generateVectorIndexes) {
      return '';
    }

    const vectorIndexes: string[] = [];

    // Check for custom configurations first
    const customConfigs = this.options.vectorIndexConfigs?.[table.tableName];
    if (customConfigs && customConfigs.length > 0) {
      for (const config of customConfigs) {
        const filterFieldsStr =
          config.filterFields.length > 0
            ? `, filterFields: [${config.filterFields.map((f) => `"${f}"`).join(', ')}]`
            : '';
        vectorIndexes.push(
          `    .vectorIndex("${config.indexName}", { vectorField: "${config.vectorField}", dimensions: ${config.dimensions}${filterFieldsStr} })`
        );
      }
    } else {
      // Auto-detect vector/embedding fields
      // Common naming patterns: embedding, embeddings, vector, vectors, feature_vector, etc.
      const vectorFieldPatterns = [
        /embedding/i,
        /vector/i,
        /features?$/i,
        /encode/i,
      ];

      const vectorFields = table.columns.filter((col) => {
        const name = col.columnName.toLowerCase();
        const cleanType = col.dataType.split('(')[0].toLowerCase();

        // Check if column name matches vector patterns
        const nameMatches = vectorFieldPatterns.some((pattern) =>
          pattern.test(name)
        );

        // Check if type is array (PostgreSQL array types often store vectors)
        const isArrayType =
          col.dataType.includes('[]') ||
          cleanType === 'vector' || // pgvector type
          (cleanType === 'real' && col.dataType.includes('[]')) ||
          (cleanType === 'float4' && col.dataType.includes('[]')) ||
          (cleanType === 'double precision' && col.dataType.includes('[]'));

        return nameMatches || isArrayType;
      });

      // Generate vector index for each detected vector field
      for (const col of vectorFields) {
        const fieldName = toCamelCase(col.columnName);
        const indexName = `vector_${fieldName}`;

        // Find potential filter fields
        const filterFields = table.columns
          .filter((c) => {
            if (c.columnName === col.columnName) return false;
            if (this.shouldSkipColumn(c)) return false;
            const cleanType = c.dataType.split('(')[0].toLowerCase();
            return (
              c.isForeignKey ||
              [
                'boolean',
                'bool',
                'integer',
                'int',
                'smallint',
                'text',
                'varchar',
              ].includes(cleanType)
            );
          })
          .slice(0, 3) // Limit to 3 filter fields
          .map((c) => toCamelCase(c.columnName));

        const filterFieldsStr =
          filterFields.length > 0
            ? `, filterFields: [${filterFields.map((f) => `"${f}"`).join(', ')}]`
            : '';

        vectorIndexes.push(
          `    .vectorIndex("${indexName}", { vectorField: "${fieldName}", dimensions: ${this.options.defaultVectorDimensions}${filterFieldsStr} })`
        );
      }
    }

    if (vectorIndexes.length === 0) {
      return '';
    }

    return '\n' + vectorIndexes.join('\n');
  }

  /**
   * Get search index configurations for statistics
   */
  getSearchIndexCount(tables: TableInfo[]): number {
    if (!this.options.generateSearchIndexes) {
      return 0;
    }

    let count = 0;
    for (const table of tables) {
      const customConfigs = this.options.searchIndexConfigs?.[table.tableName];
      if (customConfigs) {
        count += customConfigs.length;
      } else {
        // Count auto-detected text fields
        count += table.columns.filter((col) => {
          const cleanType = col.dataType.split('(')[0].toLowerCase();
          return ['text', 'varchar', 'character varying', 'citext'].includes(
            cleanType
          );
        }).length;
      }
    }
    return count;
  }

  /**
   * Get vector index configurations for statistics
   */
  getVectorIndexCount(tables: TableInfo[]): number {
    if (!this.options.generateVectorIndexes) {
      return 0;
    }

    let count = 0;
    for (const table of tables) {
      const customConfigs = this.options.vectorIndexConfigs?.[table.tableName];
      if (customConfigs) {
        count += customConfigs.length;
      } else {
        // Count auto-detected vector fields
        const vectorFieldPatterns = [
          /embedding/i,
          /vector/i,
          /features?$/i,
          /encode/i,
        ];
        count += table.columns.filter((col) => {
          const name = col.columnName.toLowerCase();
          const cleanType = col.dataType.split('(')[0].toLowerCase();
          const nameMatches = vectorFieldPatterns.some((pattern) =>
            pattern.test(name)
          );
          const isArrayType =
            col.dataType.includes('[]') || cleanType === 'vector';
          return nameMatches || isArrayType;
        }).length;
      }
    }
    return count;
  }

  // Using shared toCamelCase from ../../shared/types.js
}
