/**
 * Convex Type Generator
 *
 * Generates TypeScript type definitions for Convex:
 * - Document types: Full document with _id and _creationTime
 * - Input types: For creating documents
 * - Update types: For partial updates
 * - With relations: Types that include related documents
 */

import type {
  TableInfo,
  ColumnInfo,
} from '../../introspector/schema-introspector.js';
import type { TypeGeneratorResult } from '../../convex/types.js';

/**
 * Generates TypeScript type definitions for Convex tables
 */
export class TypeGenerator {
  /**
   * Generate all types for a table
   */
  generate(table: TableInfo): TypeGeneratorResult {
    const tableName = table.tableName;
    const pascalName = this.toPascalCase(tableName);

    const types: string[] = [];

    // 1. Base document type (with _id and _creationTime)
    types.push(this.generateDocumentType(table, pascalName));

    // 2. Create input type
    types.push(this.generateCreateInputType(table, pascalName));

    // 3. Update input type (partial)
    types.push(this.generateUpdateInputType(table, pascalName));

    // 4. With relations type (if has foreign keys)
    if (table.foreignKeys.length > 0) {
      types.push(this.generateWithRelationsType(table, pascalName));
    }

    // 5. List response type
    types.push(this.generateListResponseType(pascalName));

    const content = `// Generated TypeScript types for ${table.tableName}
// Do not edit this file directly - it will be overwritten

import type { Id } from "./_generated/dataModel";

${types.join('\n\n')}
`;

    return { content, count: types.length };
  }

  /**
   * Generate the main document type
   */
  private generateDocumentType(table: TableInfo, pascalName: string): string {
    const fields = table.columns
      .filter((col) => !this.shouldSkipColumn(col))
      .map((col) => {
        const fieldName = this.toCamelCase(col.columnName);
        const tsType = this.getTypeScriptType(col, table);
        const optional = col.isNullable || col.columnDefault ? '?' : '';
        const comment = col.description ? `  /** ${col.description} */\n` : '';
        return `${comment}  ${fieldName}${optional}: ${tsType};`;
      })
      .join('\n');

    return `/**
 * ${pascalName} document type
 * Represents a full document from the ${table.tableName} table
 */
export interface ${pascalName} {
  /** Unique document identifier */
  _id: Id<"${table.tableName}">;
  /** Document creation timestamp */
  _creationTime: number;
${fields}
}`;
  }

  /**
   * Generate create input type
   */
  private generateCreateInputType(
    table: TableInfo,
    pascalName: string
  ): string {
    const createFields = this.getCreateFields(table);
    const fields = createFields
      .map((col) => {
        const fieldName = this.toCamelCase(col.columnName);
        const tsType = this.getTypeScriptType(col, table);
        const optional = col.isNullable || col.columnDefault ? '?' : '';
        return `  ${fieldName}${optional}: ${tsType};`;
      })
      .join('\n');

    return `/**
 * Input type for creating a new ${pascalName}
 */
export interface Create${pascalName}Input {
${fields}
}`;
  }

  /**
   * Generate update input type (all optional)
   */
  private generateUpdateInputType(
    table: TableInfo,
    pascalName: string
  ): string {
    const updateFields = this.getUpdateFields(table);
    const fields = updateFields
      .map((col) => {
        const fieldName = this.toCamelCase(col.columnName);
        const tsType = this.getTypeScriptType(col, table);
        return `  ${fieldName}?: ${tsType};`;
      })
      .join('\n');

    return `/**
 * Input type for updating a ${pascalName}
 * All fields are optional for partial updates
 */
export interface Update${pascalName}Input {
${fields}
}`;
  }

  /**
   * Generate type with expanded relations
   */
  private generateWithRelationsType(
    table: TableInfo,
    pascalName: string
  ): string {
    const relationFields = table.foreignKeys
      .map((fk) => {
        const fieldName = this.toCamelCase(fk.columnName);
        const relatedPascal = this.toPascalCase(fk.referencedTable);
        // Remove the Id suffix if present (e.g., userId -> user)
        const relationName = fieldName.replace(/Id$/, '');
        return `  /** Related ${relatedPascal} document */\n  ${relationName}?: ${relatedPascal} | null;`;
      })
      .join('\n');

    return `/**
 * ${pascalName} with expanded relations
 * Includes related documents instead of just IDs
 */
export interface ${pascalName}WithRelations extends ${pascalName} {
${relationFields}
}`;
  }

  /**
   * Generate list response type with pagination
   */
  private generateListResponseType(pascalName: string): string {
    return `/**
 * Paginated list response for ${pascalName}
 */
export interface ${pascalName}ListResponse {
  /** Array of ${pascalName} documents */
  items: ${pascalName}[];
  /** Cursor for next page, if more results exist */
  nextCursor?: string;
  /** Whether more results are available */
  hasMore: boolean;
}`;
  }

  /**
   * Get fields for create operation
   */
  private getCreateFields(table: TableInfo): ColumnInfo[] {
    return table.columns.filter((col) => {
      if (col.isIdentity) return false;
      if (col.columnDefault?.includes('nextval')) return false;
      if (col.isPrimaryKey && col.columnName.toLowerCase() === 'id')
        return false;
      return true;
    });
  }

  /**
   * Get fields for update operation
   */
  private getUpdateFields(table: TableInfo): ColumnInfo[] {
    return table.columns.filter((col) => {
      if (col.isPrimaryKey) return false;
      if (col.isIdentity) return false;
      return true;
    });
  }

  /**
   * Check if column should be skipped
   */
  private shouldSkipColumn(column: ColumnInfo): boolean {
    if (column.isPrimaryKey && column.isIdentity) return true;
    if (column.columnName.toLowerCase() === 'id' && column.isPrimaryKey)
      return true;
    return false;
  }

  /**
   * Get TypeScript type for a column
   */
  private getTypeScriptType(column: ColumnInfo, table: TableInfo): string {
    // Handle foreign keys
    if (column.isForeignKey && column.foreignKeyTable) {
      return `Id<"${column.foreignKeyTable}">`;
    }

    return this.mapToTypeScriptType(column);
  }

  /**
   * Map PostgreSQL type to TypeScript type
   */
  private mapToTypeScriptType(column: ColumnInfo): string {
    const cleanType = column.dataType.split('(')[0].toLowerCase();

    // Handle arrays
    if (column.dataType.includes('[]')) {
      const baseType = cleanType.replace('[]', '');
      const elementType = this.mapSimpleType(baseType);
      return `${elementType}[]`;
    }

    return this.mapSimpleType(cleanType);
  }

  /**
   * Map simple PostgreSQL type to TypeScript
   */
  private mapSimpleType(pgType: string): string {
    const mapping: Record<string, string> = {
      // String types
      text: 'string',
      varchar: 'string',
      'character varying': 'string',
      character: 'string',
      char: 'string',
      uuid: 'string',
      citext: 'string',
      time: 'string',
      interval: 'string',

      // Number types
      integer: 'number',
      int: 'number',
      int4: 'number',
      smallint: 'number',
      bigint: 'number',
      int8: 'number',
      serial: 'number',
      bigserial: 'number',
      decimal: 'number',
      numeric: 'number',
      real: 'number',
      float4: 'number',
      'double precision': 'number',
      float8: 'number',
      money: 'number',
      timestamp: 'number',
      'timestamp without time zone': 'number',
      'timestamp with time zone': 'number',
      timestamptz: 'number',
      date: 'number',

      // Boolean
      boolean: 'boolean',
      bool: 'boolean',

      // JSON - use unknown for type safety
      json: 'unknown',
      jsonb: 'unknown',

      // Binary
      bytea: 'ArrayBuffer',
    };

    return mapping[pgType] || 'string';
  }

  /**
   * Convert snake_case to camelCase
   */
  private toCamelCase(str: string): string {
    return str.replace(/_([a-z])/g, (_, letter) => letter.toUpperCase());
  }

  /**
   * Convert to PascalCase
   */
  private toPascalCase(str: string): string {
    const camel = this.toCamelCase(str);
    return camel.charAt(0).toUpperCase() + camel.slice(1);
  }

  /**
   * Generate types for all tables in schema
   */
  generateAll(tables: TableInfo[]): {
    types: Map<string, TypeGeneratorResult>;
    indexContent: string;
  } {
    const types = new Map<string, TypeGeneratorResult>();

    for (const table of tables) {
      types.set(table.tableName, this.generate(table));
    }

    // Generate index file that re-exports all types
    const exports = tables
      .map((t) => {
        const pascalName = this.toPascalCase(t.tableName);
        return `export type { ${pascalName}, Create${pascalName}Input, Update${pascalName}Input, ${pascalName}ListResponse } from "./${t.tableName}/types";`;
      })
      .join('\n');

    const indexContent = `// Generated type exports
// Do not edit this file directly - it will be overwritten

${exports}
`;

    return { types, indexContent };
  }
}
