/**
 * Convex Validator Generator
 *
 * Generates reusable validator objects for Convex:
 * - Base validators: Full document validation
 * - Create validators: For creating new documents
 * - Update validators: For partial updates (all optional)
 * - List validators: For pagination args
 * - Filter validators: For filtering queries
 */

import type {
  TableInfo,
  ColumnInfo,
} from '../../introspector/schema-introspector.js';
import type { ValidatorGeneratorResult } from '../../convex/types.js';
import {
  toCamelCase,
  toPascalCase,
  escapeFieldName,
} from '../../utils/naming.js';
import { BaseConvexGenerator } from './base-convex-generator.js';
import type { BaseGeneratorOptions } from './base-convex-generator.js';

const DEFAULT_OPTIONS: BaseGeneratorOptions = {};

/**
 * Generates Convex validator objects
 */
export class ValidatorGenerator extends BaseConvexGenerator<BaseGeneratorOptions> {
  constructor(options: BaseGeneratorOptions = {}) {
    super(DEFAULT_OPTIONS, options);
  }
  /**
   * Generate all validators for a table
   */
  generate(table: TableInfo): ValidatorGeneratorResult {
    const tableName = table.tableName;
    const pascalName = toPascalCase(tableName);
    const camelName = toCamelCase(tableName);

    const validators: string[] = [];

    // 1. Base validator - represents the full document shape
    validators.push(this.generateBaseValidator(table, camelName, pascalName));

    // 2. Create validator - fields needed for creation
    validators.push(this.generateCreateValidator(table, camelName, pascalName));

    // 3. Update validator - all fields optional for partial updates
    validators.push(this.generateUpdateValidator(table, camelName, pascalName));

    // 4. List args validator - pagination arguments
    validators.push(this.generateListArgsValidator(camelName, pascalName));

    // 5. Filter validator - common filter fields
    validators.push(this.generateFilterValidator(table, camelName, pascalName));

    const content = `// Generated validators for ${table.tableName}
// Do not edit this file directly - it will be overwritten

import { v } from "convex/values";

${validators.join('\n\n')}

/**
 * Exported validators for ${pascalName}
 */
export const ${camelName}Validators = {
  base: ${camelName}Validator,
  create: create${pascalName}Validator,
  update: update${pascalName}Validator,
  listArgs: ${camelName}ListArgsValidator,
  filter: ${camelName}FilterValidator,
};
`;

    return { content, count: validators.length };
  }

  /**
   * Generate base validator (full document shape)
   */
  private generateBaseValidator(
    table: TableInfo,
    camelName: string,
    pascalName: string
  ): string {
    const fields = table.columns
      .filter((col) => !this.shouldSkipColumn(col))
      .map((col) => {
        const fieldName = escapeFieldName(toCamelCase(col.columnName));
        const validator = this.getConvexValidator(col);
        return `  ${fieldName}: ${validator}`;
      })
      .join(',\n');

    return `/**
 * Base validator for ${pascalName} documents
 * Represents the full document shape (excluding _id and _creationTime)
 */
export const ${camelName}Validator = v.object({
${fields},
});`;
  }

  /**
   * Generate create validator (excludes auto-generated fields)
   */
  private generateCreateValidator(
    table: TableInfo,
    camelName: string,
    pascalName: string
  ): string {
    const createFields = this.getCreateFields(table);
    const fields = createFields
      .map((col) => {
        const fieldName = escapeFieldName(toCamelCase(col.columnName));
        const validator = this.getConvexValidator(col);
        return `  ${fieldName}: ${validator}`;
      })
      .join(',\n');

    return `/**
 * Validator for creating new ${pascalName} documents
 * Excludes auto-generated fields
 */
export const create${pascalName}Validator = v.object({
${fields},
});`;
  }

  /**
   * Generate update validator (all fields optional)
   */
  private generateUpdateValidator(
    table: TableInfo,
    camelName: string,
    pascalName: string
  ): string {
    const updateFields = this.getUpdateFields(table);
    const fields = updateFields
      .map((col) => {
        const fieldName = escapeFieldName(toCamelCase(col.columnName));
        let validator = this.getConvexValidator(col);
        // Wrap in optional if not already
        if (!validator.startsWith('v.optional(')) {
          validator = `v.optional(${validator})`;
        }
        return `  ${fieldName}: ${validator}`;
      })
      .join(',\n');

    return `/**
 * Validator for updating ${pascalName} documents
 * All fields are optional for partial updates
 */
export const update${pascalName}Validator = v.object({
${fields},
});`;
  }

  /**
   * Generate list args validator (pagination)
   */
  private generateListArgsValidator(
    camelName: string,
    pascalName: string
  ): string {
    return `/**
 * Validator for ${pascalName} list pagination arguments
 */
export const ${camelName}ListArgsValidator = v.object({
  limit: v.optional(v.number()),
  cursor: v.optional(v.string()),
  order: v.optional(v.union(v.literal("asc"), v.literal("desc"))),
});`;
  }

  /**
   * Generate filter validator for common filtering scenarios
   */
  private generateFilterValidator(
    table: TableInfo,
    camelName: string,
    pascalName: string
  ): string {
    const filterableFields = this.getFilterableFields(table);

    if (filterableFields.length === 0) {
      return `/**
 * Validator for filtering ${pascalName} documents
 */
export const ${camelName}FilterValidator = v.object({});`;
    }

    const fields = filterableFields
      .map((col) => {
        const fieldName = escapeFieldName(toCamelCase(col.columnName));
        const baseValidator = this.getConvexValidator(col);
        // Make filter fields optional
        const validator = baseValidator.startsWith('v.optional(')
          ? baseValidator
          : `v.optional(${baseValidator})`;
        return `  ${fieldName}: ${validator}`;
      })
      .join(',\n');

    return `/**
 * Validator for filtering ${pascalName} documents
 * All filter fields are optional
 */
export const ${camelName}FilterValidator = v.object({
${fields},
});`;
  }

  /**
   * Get filterable fields (foreign keys, indexed fields, common types)
   */
  private getFilterableFields(table: TableInfo): ColumnInfo[] {
    const indexedColumns = new Set(table.indexes.map((idx) => idx.columnName));
    const fkColumns = new Set(table.foreignKeys.map((fk) => fk.columnName));

    return table.columns.filter((col) => {
      // Skip large text fields
      if (col.characterMaximumLength && col.characterMaximumLength > 255)
        return false;
      // Include indexed columns
      if (indexedColumns.has(col.columnName)) return true;
      // Include foreign keys
      if (fkColumns.has(col.columnName)) return true;
      // Include common filter types
      const simpleTypes = [
        'boolean',
        'bool',
        'integer',
        'int',
        'smallint',
        'date',
      ];
      const baseType = col.dataType.split('(')[0].toLowerCase();
      if (simpleTypes.includes(baseType)) return true;
      // Include status/type columns by naming convention
      const filterNames = [
        'status',
        'type',
        'state',
        'kind',
        'category',
        'active',
        'enabled',
      ];
      if (
        filterNames.some((name) => col.columnName.toLowerCase().includes(name))
      )
        return true;
      return false;
    });
  }
}
