import { promises as fs } from 'fs';
import { join } from 'path';
import {
  TableInfo,
  SchemaInfo,
  ColumnInfo,
} from '../introspector/schema-introspector.js';
import { TypeMapper } from '../mapper/type-mapper.js';
import { toCamelCase, toPascalCase, toKebabCase, escapeFieldName } from '../utils/naming.js';

export interface GeneratorOptions {
  outputDir: string;
  generateModels: boolean;
  generateRepositories: boolean;
  generateServices: boolean;
  generateValidators: boolean;
  generateConvexSchema: boolean;
  generateMigrations: boolean;
  useZod: boolean;
  useClassValidator: boolean;
}

export class CodeGenerator {
  private typeMapper: TypeMapper;
  private options: GeneratorOptions;

  constructor(options: GeneratorOptions, typeMapper?: TypeMapper) {
    this.options = options;
    this.typeMapper = typeMapper || new TypeMapper();
  }

  async generateFromSchema(schema: SchemaInfo): Promise<void> {
    await this.ensureDirectories();

    for (const table of schema.tables) {
      if (this.options.generateModels) {
        await this.generateModel(table);
      }

      if (this.options.generateRepositories) {
        await this.generateRepository(table);
      }

      if (this.options.generateServices) {
        await this.generateService(table);
      }

      if (this.options.generateValidators) {
        await this.generateValidator(table);
      }

      if (this.options.generateConvexSchema) {
        await this.generateConvexSchema(table);
      }
    }

    // Generate index files
    await this.generateIndexFiles(schema);
  }

  private async ensureDirectories(): Promise<void> {
    const dirs = ['models', 'repositories', 'services', 'validators', 'convex'];

    for (const dir of dirs) {
      const dirPath = join(this.options.outputDir, dir);
      await fs.mkdir(dirPath, { recursive: true });
    }
  }

  private async generateModel(table: TableInfo): Promise<void> {
    const modelName = toPascalCase(table.tableName);
    const fileName = `${toKebabCase(table.tableName)}.model.ts`;
    const filePath = join(this.options.outputDir, 'models', fileName);

    const interfaceCode = this.typeMapper.generateTableInterface(
      table.tableName,
      table.columns
    );
    const createInputCode = this.typeMapper.generateCreateInput(
      table.tableName,
      table.columns
    );
    const updateInputCode = this.typeMapper.generateUpdateInput(
      table.tableName,
      table.columns
    );

    const content = `// Generated model for ${table.tableName}
// Do not edit this file directly - it will be overwritten

${interfaceCode}

${createInputCode}

${updateInputCode}

export type ${modelName}Id = ${this.getPrimaryKeyType(table)};

export const ${modelName.toUpperCase()}_TABLE_NAME = '${table.tableName}' as const;
`;

    await fs.writeFile(filePath, content, 'utf8');
  }

  private async generateRepository(table: TableInfo): Promise<void> {
    const modelName = toPascalCase(table.tableName);
    const repoName = `${modelName}Repository`;
    const fileName = `${toKebabCase(table.tableName)}.repository.ts`;
    const filePath = join(this.options.outputDir, 'repositories', fileName);

    const primaryKeyCol = table.columns.find((col) => col.isPrimaryKey);
    const primaryKeyType = primaryKeyCol
      ? this.typeMapper.mapColumnToTypeScript(primaryKeyCol).type
      : 'number';

    const content = `// Generated repository for ${table.tableName}
// Do not edit this file directly - it will be overwritten

import { Pool } from 'pg';
import { 
  ${modelName}, 
  Create${modelName}Input, 
  Update${modelName}Input,
  ${modelName.toUpperCase()}_TABLE_NAME
} from '../models/${toKebabCase(table.tableName)}.model.js';

export class ${repoName} {
  constructor(private db: Pool) {}

  async findAll(): Promise<${modelName}[]> {
    const query = \`SELECT * FROM \${${modelName.toUpperCase()}_TABLE_NAME}\`;
    const result = await this.db.query(query);
    return result.rows;
  }

  async findById(id: ${primaryKeyType}): Promise<${modelName} | null> {
    const query = \`SELECT * FROM \${${modelName.toUpperCase()}_TABLE_NAME} WHERE ${primaryKeyCol?.columnName} = $1\`;
    const result = await this.db.query(query, [id]);
    return result.rows[0] || null;
  }

  async create(data: Create${modelName}Input): Promise<${modelName}> {
    const columns = Object.keys(data).join(', ');
    const placeholders = Object.keys(data).map((_, index) => \`$\${index + 1}\`).join(', ');
    const values = Object.values(data);
    
    const query = \`
      INSERT INTO \${${modelName.toUpperCase()}_TABLE_NAME} (\${columns})
      VALUES (\${placeholders})
      RETURNING *
    \`;
    
    const result = await this.db.query(query, values);
    return result.rows[0];
  }

  async update(id: ${primaryKeyType}, data: Update${modelName}Input): Promise<${modelName} | null> {
    const entries = Object.entries(data).filter(([_, value]) => value !== undefined);
    if (entries.length === 0) {
      return this.findById(id);
    }

    const setClause = entries.map(([key], index) => \`\${key} = $\${index + 2}\`).join(', ');
    const values = [id, ...entries.map(([_, value]) => value)];
    
    const query = \`
      UPDATE \${${modelName.toUpperCase()}_TABLE_NAME}
      SET \${setClause}
      WHERE ${primaryKeyCol?.columnName} = $1
      RETURNING *
    \`;
    
    const result = await this.db.query(query, values);
    return result.rows[0] || null;
  }

  async delete(id: ${primaryKeyType}): Promise<boolean> {
    const query = \`DELETE FROM \${${modelName.toUpperCase()}_TABLE_NAME} WHERE ${primaryKeyCol?.columnName} = $1\`;
    const result = await this.db.query(query, [id]);
    return result.rowCount > 0;
  }

  async findBy(criteria: Partial<${modelName}>): Promise<${modelName}[]> {
    const entries = Object.entries(criteria).filter(([_, value]) => value !== undefined);
    if (entries.length === 0) {
      return this.findAll();
    }

    const whereClause = entries.map(([key], index) => \`\${key} = $\${index + 1}\`).join(' AND ');
    const values = entries.map(([_, value]) => value);
    
    const query = \`SELECT * FROM \${${modelName.toUpperCase()}_TABLE_NAME} WHERE \${whereClause}\`;
    const result = await this.db.query(query, values);
    return result.rows;
  }

  async count(): Promise<number> {
    const query = \`SELECT COUNT(*) as count FROM \${${modelName.toUpperCase()}_TABLE_NAME}\`;
    const result = await this.db.query(query);
    return parseInt(result.rows[0].count);
  }

  async exists(id: ${primaryKeyType}): Promise<boolean> {
    const query = \`SELECT 1 FROM \${${modelName.toUpperCase()}_TABLE_NAME} WHERE ${primaryKeyCol?.columnName} = $1 LIMIT 1\`;
    const result = await this.db.query(query, [id]);
    return result.rows.length > 0;
  }
}
`;

    await fs.writeFile(filePath, content, 'utf8');
  }

  private async generateService(table: TableInfo): Promise<void> {
    const modelName = toPascalCase(table.tableName);
    const serviceName = `${modelName}Service`;
    const repoName = `${modelName}Repository`;
    const fileName = `${toKebabCase(table.tableName)}.service.ts`;
    const filePath = join(this.options.outputDir, 'services', fileName);

    const primaryKeyCol = table.columns.find((col) => col.isPrimaryKey);
    const primaryKeyType = primaryKeyCol
      ? this.typeMapper.mapColumnToTypeScript(primaryKeyCol).type
      : 'number';

    const content = `// Generated service for ${table.tableName}
// Do not edit this file directly - it will be overwritten

import { 
  ${modelName}, 
  Create${modelName}Input, 
  Update${modelName}Input 
} from '../models/${toKebabCase(table.tableName)}.model.js';
import { ${repoName} } from '../repositories/${toKebabCase(table.tableName)}.repository.js';

export interface ${serviceName}Interface {
  getAll(): Promise<${modelName}[]>;
  getById(id: ${primaryKeyType}): Promise<${modelName} | null>;
  create(data: Create${modelName}Input): Promise<${modelName}>;
  update(id: ${primaryKeyType}, data: Update${modelName}Input): Promise<${modelName} | null>;
  delete(id: ${primaryKeyType}): Promise<boolean>;
  search(criteria: Partial<${modelName}>): Promise<${modelName}[]>;
}

export class ${serviceName} implements ${serviceName}Interface {
  constructor(private repository: ${repoName}) {}

  async getAll(): Promise<${modelName}[]> {
    return this.repository.findAll();
  }

  async getById(id: ${primaryKeyType}): Promise<${modelName} | null> {
    return this.repository.findById(id);
  }

  async create(data: Create${modelName}Input): Promise<${modelName}> {
    // Add business logic validation here
    return this.repository.create(data);
  }

  async update(id: ${primaryKeyType}, data: Update${modelName}Input): Promise<${modelName} | null> {
    // Check if entity exists
    const existing = await this.repository.findById(id);
    if (!existing) {
      throw new Error(\`${modelName} with id \${id} not found\`);
    }

    // Add business logic validation here
    return this.repository.update(id, data);
  }

  async delete(id: ${primaryKeyType}): Promise<boolean> {
    // Check if entity exists
    const existing = await this.repository.findById(id);
    if (!existing) {
      throw new Error(\`${modelName} with id \${id} not found\`);
    }

    // Add cascade delete logic here if needed
    return this.repository.delete(id);
  }

  async search(criteria: Partial<${modelName}>): Promise<${modelName}[]> {
    return this.repository.findBy(criteria);
  }

  async getCount(): Promise<number> {
    return this.repository.count();
  }

  async exists(id: ${primaryKeyType}): Promise<boolean> {
    return this.repository.exists(id);
  }
}
`;

    await fs.writeFile(filePath, content, 'utf8');
  }

  private async generateValidator(table: TableInfo): Promise<void> {
    if (!this.options.useZod && !this.options.useClassValidator) {
      return;
    }

    const fileName = `${toKebabCase(table.tableName)}.validator.ts`;
    const filePath = join(this.options.outputDir, 'validators', fileName);

    let content = '';

    if (this.options.useZod) {
      content = this.generateZodValidator(table);
    } else if (this.options.useClassValidator) {
      content = this.generateClassValidator(table);
    }

    await fs.writeFile(filePath, content, 'utf8');
  }

  private generateZodValidator(table: TableInfo): string {
    const modelName = toPascalCase(table.tableName);

    const zodFields = table.columns
      .map((column) => {
        const fieldName = escapeFieldName(toCamelCase(column.columnName));
        let zodType = this.getZodType(column);

        if (column.isNullable) {
          zodType = `${zodType}.nullable()`;
        }

        if (column.columnDefault) {
          zodType = `${zodType}.optional()`;
        }

        return `  ${fieldName}: ${zodType}`;
      })
      .join(',\n');

    return `// Generated Zod validator for ${table.tableName}
// Do not edit this file directly - it will be overwritten

import { z } from 'zod';

export const ${modelName}Schema = z.object({
${zodFields}
});

export const Create${modelName}Schema = ${modelName}Schema.omit({
  ${table.columns
    .filter((col) => col.isIdentity || col.columnDefault?.includes('nextval'))
    .map((col) => `${escapeFieldName(toCamelCase(col.columnName))}: true`)
    .join(',\n  ')}
});

export const Update${modelName}Schema = ${modelName}Schema.partial().omit({
  ${table.columns
    .filter((col) => col.isPrimaryKey || col.isIdentity)
    .map((col) => `${escapeFieldName(toCamelCase(col.columnName))}: true`)
    .join(',\n  ')}
});

export type ${modelName}ValidationError = z.ZodError<z.infer<typeof ${modelName}Schema>>;
`;
  }

  private generateClassValidator(table: TableInfo): string {
    const modelName = toPascalCase(table.tableName);

    const validatorFields = table.columns
      .map((column) => {
        const fieldName = escapeFieldName(toCamelCase(column.columnName));
        const decorators = this.getClassValidatorDecorators(column);

        return `  ${decorators.join('\n  ')}
  ${fieldName}${column.isNullable ? '?' : ''}: ${this.typeMapper.mapColumnToTypeScript(column).type};`;
      })
      .join('\n\n');

    return `// Generated class-validator for ${table.tableName}
// Do not edit this file directly - it will be overwritten

import { 
  IsString, 
  IsNumber, 
  IsBoolean, 
  IsDate, 
  IsOptional, 
  IsUUID,
  MaxLength,
  Min,
  Max
} from 'class-validator';

export class ${modelName}Validator {
${validatorFields}
}
`;
  }

  private async generateConvexSchema(table: TableInfo): Promise<void> {
    const fileName = `${toKebabCase(table.tableName)}.convex.ts`;
    const filePath = join(this.options.outputDir, 'convex', fileName);

    const convexFields = table.columns
      .map((column) => {
        const fieldName = escapeFieldName(toCamelCase(column.columnName));
        const convexType = this.typeMapper.mapColumnToConvex(column).validator;

        return `    ${fieldName}: ${convexType}`;
      })
      .join(',\n');

    const content = `// Generated Convex schema for ${table.tableName}
// Do not edit this file directly - it will be overwritten

import { defineTable } from 'convex/server';
import { v } from 'convex/values';

export const ${toCamelCase(table.tableName)} = defineTable({
${convexFields}
});

export default ${toCamelCase(table.tableName)};
`;

    await fs.writeFile(filePath, content, 'utf8');
  }

  private async generateIndexFiles(schema: SchemaInfo): Promise<void> {
    // Generate models index
    const modelsIndex = schema.tables
      .map((table) => {
        const kebabName = toKebabCase(table.tableName);
        return `export * from './${kebabName}.model.js';`;
      })
      .join('\n');

    await fs.writeFile(
      join(this.options.outputDir, 'models', 'index.ts'),
      `// Generated index file for models\n// Do not edit this file directly - it will be overwritten\n\n${modelsIndex}\n`,
      'utf8'
    );

    // Generate repositories index
    const repositoriesIndex = schema.tables
      .map((table) => {
        const kebabName = toKebabCase(table.tableName);
        return `export * from './${kebabName}.repository.js';`;
      })
      .join('\n');

    await fs.writeFile(
      join(this.options.outputDir, 'repositories', 'index.ts'),
      `// Generated index file for repositories\n// Do not edit this file directly - it will be overwritten\n\n${repositoriesIndex}\n`,
      'utf8'
    );

    // Generate services index
    const servicesIndex = schema.tables
      .map((table) => {
        const kebabName = toKebabCase(table.tableName);
        return `export * from './${kebabName}.service.js';`;
      })
      .join('\n');

    await fs.writeFile(
      join(this.options.outputDir, 'services', 'index.ts'),
      `// Generated index file for services\n// Do not edit this file directly - it will be overwritten\n\n${servicesIndex}\n`,
      'utf8'
    );
  }

  private getPrimaryKeyType(table: TableInfo): string {
    const primaryKeyCol = table.columns.find((col) => col.isPrimaryKey);
    if (!primaryKeyCol) return 'number';

    return this.typeMapper.mapColumnToTypeScript(primaryKeyCol).type;
  }

  private getZodType(column: ColumnInfo): string {
    switch (column.dataType.toLowerCase()) {
      case 'text':
      case 'varchar':
      case 'character varying':
      case 'uuid':
        return 'z.string()';
      case 'integer':
      case 'bigint':
      case 'smallint':
      case 'serial':
        return 'z.number()';
      case 'boolean':
        return 'z.boolean()';
      case 'timestamp':
      case 'date':
        return 'z.date()';
      case 'json':
      case 'jsonb':
        return 'z.record(z.unknown())';
      default:
        return 'z.string()';
    }
  }

  private getClassValidatorDecorators(column: ColumnInfo): string[] {
    const decorators: string[] = [];

    if (column.isNullable) {
      decorators.push('@IsOptional()');
    }

    switch (column.dataType.toLowerCase()) {
      case 'text':
      case 'varchar':
      case 'character varying':
        decorators.push('@IsString()');
        if (column.characterMaximumLength) {
          decorators.push(`@MaxLength(${column.characterMaximumLength})`);
        }
        break;
      case 'uuid':
        decorators.push('@IsUUID()');
        break;
      case 'integer':
      case 'bigint':
      case 'smallint':
      case 'serial':
        decorators.push('@IsNumber()');
        break;
      case 'boolean':
        decorators.push('@IsBoolean()');
        break;
      case 'timestamp':
      case 'date':
        decorators.push('@IsDate()');
        break;
      default:
        decorators.push('@IsString()');
    }

    return decorators;
  }

}
